#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 75
#define LARGE_STATE_COUNT 19
#define SYMBOL_COUNT 40
#define ALIAS_COUNT 0
#define TOKEN_COUNT 28
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 3

enum {
  sym_identifier = 1,
  sym_shell_bang = 2,
  anon_sym_BANG = 3,
  anon_sym_DASH = 4,
  anon_sym_and = 5,
  anon_sym_or = 6,
  anon_sym_PLUS = 7,
  anon_sym_STAR = 8,
  anon_sym_SLASH = 9,
  anon_sym_LT = 10,
  anon_sym_LT_EQ = 11,
  anon_sym_EQ_EQ = 12,
  anon_sym_BANG_EQ = 13,
  anon_sym_GT_EQ = 14,
  anon_sym_GT = 15,
  anon_sym_LBRACK = 16,
  anon_sym_COMMA = 17,
  anon_sym_RBRACK = 18,
  sym_number = 19,
  anon_sym_DQUOTE = 20,
  sym_unescaped_double_string_fragment = 21,
  sym_escape_sequence = 22,
  anon_sym_true = 23,
  anon_sym_false = 24,
  sym_nil = 25,
  anon_sym_SLASH_SLASH = 26,
  aux_sym_comment_token1 = 27,
  sym_source_file = 28,
  sym__expression = 29,
  sym_unary_expression = 30,
  sym_binary_expression = 31,
  sym_array = 32,
  sym__primary = 33,
  sym_string = 34,
  sym_boolean = 35,
  sym_comment = 36,
  aux_sym_source_file_repeat1 = 37,
  aux_sym_array_repeat1 = 38,
  aux_sym_string_repeat1 = 39,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_shell_bang] = "shell_bang",
  [anon_sym_BANG] = "!",
  [anon_sym_DASH] = "-",
  [anon_sym_and] = "and",
  [anon_sym_or] = "or",
  [anon_sym_PLUS] = "+",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_LT] = "<",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_GT] = ">",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [sym_number] = "number",
  [anon_sym_DQUOTE] = "\"",
  [sym_unescaped_double_string_fragment] = "string_fragment",
  [sym_escape_sequence] = "escape_sequence",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_nil] = "nil",
  [anon_sym_SLASH_SLASH] = "//",
  [aux_sym_comment_token1] = "comment_token1",
  [sym_source_file] = "source_file",
  [sym__expression] = "_expression",
  [sym_unary_expression] = "unary_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_array] = "array",
  [sym__primary] = "_primary",
  [sym_string] = "string",
  [sym_boolean] = "boolean",
  [sym_comment] = "comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_array_repeat1] = "array_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_shell_bang] = sym_shell_bang,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_and] = anon_sym_and,
  [anon_sym_or] = anon_sym_or,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_number] = sym_number,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym_unescaped_double_string_fragment] = sym_unescaped_double_string_fragment,
  [sym_escape_sequence] = sym_escape_sequence,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_nil] = sym_nil,
  [anon_sym_SLASH_SLASH] = anon_sym_SLASH_SLASH,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [sym_source_file] = sym_source_file,
  [sym__expression] = sym__expression,
  [sym_unary_expression] = sym_unary_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_array] = sym_array,
  [sym__primary] = sym__primary,
  [sym_string] = sym_string,
  [sym_boolean] = sym_boolean,
  [sym_comment] = sym_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_shell_bang] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_or] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_unescaped_double_string_fragment] = {
    .visible = true,
    .named = true,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_nil] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_unary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym__primary] = {
    .visible = false,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_left = 1,
  field_operator = 2,
  field_right = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_left] = "left",
  [field_operator] = "operator",
  [field_right] = "right",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_operator, 0},
    {field_right, 1},
  [2] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 23,
  [25] = 25,
  [26] = 25,
  [27] = 27,
  [28] = 27,
  [29] = 29,
  [30] = 30,
  [31] = 30,
  [32] = 32,
  [33] = 29,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 36,
  [38] = 38,
  [39] = 35,
  [40] = 34,
  [41] = 32,
  [42] = 42,
  [43] = 38,
  [44] = 44,
  [45] = 44,
  [46] = 6,
  [47] = 5,
  [48] = 7,
  [49] = 9,
  [50] = 11,
  [51] = 15,
  [52] = 16,
  [53] = 17,
  [54] = 13,
  [55] = 18,
  [56] = 2,
  [57] = 14,
  [58] = 8,
  [59] = 59,
  [60] = 4,
  [61] = 3,
  [62] = 12,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 64,
  [67] = 65,
  [68] = 68,
  [69] = 69,
  [70] = 68,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(9);
      if (lookahead == '!') ADVANCE(11);
      if (lookahead == '"') ADVANCE(29);
      if (lookahead == '#') ADVANCE(1);
      if (lookahead == '*') ADVANCE(15);
      if (lookahead == '+') ADVANCE(14);
      if (lookahead == ',') ADVANCE(24);
      if (lookahead == '-') ADVANCE(13);
      if (lookahead == '/') ADVANCE(16);
      if (lookahead == '<') ADVANCE(17);
      if (lookahead == '=') ADVANCE(5);
      if (lookahead == '>') ADVANCE(22);
      if (lookahead == '[') ADVANCE(23);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead == ']') ADVANCE(25);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(8)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(10);
      END_STATE();
    case 2:
      if (lookahead == '!') ADVANCE(4);
      if (lookahead == '*') ADVANCE(15);
      if (lookahead == '+') ADVANCE(14);
      if (lookahead == ',') ADVANCE(24);
      if (lookahead == '-') ADVANCE(12);
      if (lookahead == '/') ADVANCE(16);
      if (lookahead == '<') ADVANCE(17);
      if (lookahead == '=') ADVANCE(5);
      if (lookahead == '>') ADVANCE(22);
      if (lookahead == ']') ADVANCE(25);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(29);
      if (lookahead == '/') ADVANCE(31);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0) ADVANCE(32);
      END_STATE();
    case 4:
      if (lookahead == '=') ADVANCE(20);
      END_STATE();
    case 5:
      if (lookahead == '=') ADVANCE(19);
      END_STATE();
    case 6:
      if (lookahead == '"' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't') ADVANCE(33);
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 8:
      if (eof) ADVANCE(9);
      if (lookahead == '!') ADVANCE(11);
      if (lookahead == '"') ADVANCE(29);
      if (lookahead == '*') ADVANCE(15);
      if (lookahead == '+') ADVANCE(14);
      if (lookahead == ',') ADVANCE(24);
      if (lookahead == '-') ADVANCE(13);
      if (lookahead == '/') ADVANCE(16);
      if (lookahead == '<') ADVANCE(17);
      if (lookahead == '=') ADVANCE(5);
      if (lookahead == '>') ADVANCE(22);
      if (lookahead == '[') ADVANCE(23);
      if (lookahead == ']') ADVANCE(25);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(8)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_shell_bang);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_BANG);
      if (lookahead == '=') ADVANCE(20);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(34);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(18);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(21);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_unescaped_double_string_fragment);
      if (lookahead == '/') ADVANCE(31);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(32);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_unescaped_double_string_fragment);
      if (lookahead == '/') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(32);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_unescaped_double_string_fragment);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(38);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '/') ADVANCE(37);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(38);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '/') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(38);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(38);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'a') ADVANCE(1);
      if (lookahead == 'f') ADVANCE(2);
      if (lookahead == 'n') ADVANCE(3);
      if (lookahead == 'o') ADVANCE(4);
      if (lookahead == 't') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'n') ADVANCE(6);
      END_STATE();
    case 2:
      if (lookahead == 'a') ADVANCE(7);
      END_STATE();
    case 3:
      if (lookahead == 'i') ADVANCE(8);
      END_STATE();
    case 4:
      if (lookahead == 'r') ADVANCE(9);
      END_STATE();
    case 5:
      if (lookahead == 'r') ADVANCE(10);
      END_STATE();
    case 6:
      if (lookahead == 'd') ADVANCE(11);
      END_STATE();
    case 7:
      if (lookahead == 'l') ADVANCE(12);
      END_STATE();
    case 8:
      if (lookahead == 'l') ADVANCE(13);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_or);
      END_STATE();
    case 10:
      if (lookahead == 'u') ADVANCE(14);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_and);
      END_STATE();
    case 12:
      if (lookahead == 's') ADVANCE(15);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_nil);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 2},
  [46] = {.lex_state = 2},
  [47] = {.lex_state = 2},
  [48] = {.lex_state = 2},
  [49] = {.lex_state = 2},
  [50] = {.lex_state = 2},
  [51] = {.lex_state = 2},
  [52] = {.lex_state = 2},
  [53] = {.lex_state = 2},
  [54] = {.lex_state = 2},
  [55] = {.lex_state = 2},
  [56] = {.lex_state = 2},
  [57] = {.lex_state = 2},
  [58] = {.lex_state = 2},
  [59] = {.lex_state = 2},
  [60] = {.lex_state = 2},
  [61] = {.lex_state = 2},
  [62] = {.lex_state = 2},
  [63] = {.lex_state = 3},
  [64] = {.lex_state = 3},
  [65] = {.lex_state = 3},
  [66] = {.lex_state = 3},
  [67] = {.lex_state = 3},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 3},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 36},
  [74] = {(TSStateId)(-1)},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_shell_bang] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
    [anon_sym_or] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_nil] = ACTIONS(1),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(72),
    [sym__expression] = STATE(10),
    [sym_unary_expression] = STATE(11),
    [sym_binary_expression] = STATE(11),
    [sym_array] = STATE(11),
    [sym__primary] = STATE(11),
    [sym_string] = STATE(7),
    [sym_boolean] = STATE(7),
    [sym_comment] = STATE(1),
    [aux_sym_source_file_repeat1] = STATE(20),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym_shell_bang] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
    [sym_number] = ACTIONS(17),
    [anon_sym_DQUOTE] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [sym_nil] = ACTIONS(7),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [2] = {
    [sym_comment] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(23),
    [sym_identifier] = ACTIONS(25),
    [anon_sym_BANG] = ACTIONS(25),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_and] = ACTIONS(25),
    [anon_sym_or] = ACTIONS(25),
    [anon_sym_PLUS] = ACTIONS(29),
    [anon_sym_STAR] = ACTIONS(31),
    [anon_sym_SLASH] = ACTIONS(33),
    [anon_sym_LT] = ACTIONS(35),
    [anon_sym_LT_EQ] = ACTIONS(37),
    [anon_sym_EQ_EQ] = ACTIONS(23),
    [anon_sym_BANG_EQ] = ACTIONS(23),
    [anon_sym_GT_EQ] = ACTIONS(37),
    [anon_sym_GT] = ACTIONS(35),
    [anon_sym_LBRACK] = ACTIONS(23),
    [sym_number] = ACTIONS(23),
    [anon_sym_DQUOTE] = ACTIONS(23),
    [anon_sym_true] = ACTIONS(25),
    [anon_sym_false] = ACTIONS(25),
    [sym_nil] = ACTIONS(25),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [3] = {
    [sym_comment] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(23),
    [sym_identifier] = ACTIONS(25),
    [anon_sym_BANG] = ACTIONS(25),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_and] = ACTIONS(39),
    [anon_sym_or] = ACTIONS(25),
    [anon_sym_PLUS] = ACTIONS(29),
    [anon_sym_STAR] = ACTIONS(31),
    [anon_sym_SLASH] = ACTIONS(33),
    [anon_sym_LT] = ACTIONS(35),
    [anon_sym_LT_EQ] = ACTIONS(37),
    [anon_sym_EQ_EQ] = ACTIONS(41),
    [anon_sym_BANG_EQ] = ACTIONS(41),
    [anon_sym_GT_EQ] = ACTIONS(37),
    [anon_sym_GT] = ACTIONS(35),
    [anon_sym_LBRACK] = ACTIONS(23),
    [sym_number] = ACTIONS(23),
    [anon_sym_DQUOTE] = ACTIONS(23),
    [anon_sym_true] = ACTIONS(25),
    [anon_sym_false] = ACTIONS(25),
    [sym_nil] = ACTIONS(25),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [4] = {
    [sym_comment] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(23),
    [sym_identifier] = ACTIONS(25),
    [anon_sym_BANG] = ACTIONS(25),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_and] = ACTIONS(25),
    [anon_sym_or] = ACTIONS(25),
    [anon_sym_PLUS] = ACTIONS(29),
    [anon_sym_STAR] = ACTIONS(31),
    [anon_sym_SLASH] = ACTIONS(33),
    [anon_sym_LT] = ACTIONS(35),
    [anon_sym_LT_EQ] = ACTIONS(37),
    [anon_sym_EQ_EQ] = ACTIONS(41),
    [anon_sym_BANG_EQ] = ACTIONS(41),
    [anon_sym_GT_EQ] = ACTIONS(37),
    [anon_sym_GT] = ACTIONS(35),
    [anon_sym_LBRACK] = ACTIONS(23),
    [sym_number] = ACTIONS(23),
    [anon_sym_DQUOTE] = ACTIONS(23),
    [anon_sym_true] = ACTIONS(25),
    [anon_sym_false] = ACTIONS(25),
    [sym_nil] = ACTIONS(25),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [5] = {
    [sym_comment] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(23),
    [sym_identifier] = ACTIONS(25),
    [anon_sym_BANG] = ACTIONS(25),
    [anon_sym_DASH] = ACTIONS(25),
    [anon_sym_and] = ACTIONS(25),
    [anon_sym_or] = ACTIONS(25),
    [anon_sym_PLUS] = ACTIONS(23),
    [anon_sym_STAR] = ACTIONS(31),
    [anon_sym_SLASH] = ACTIONS(33),
    [anon_sym_LT] = ACTIONS(25),
    [anon_sym_LT_EQ] = ACTIONS(23),
    [anon_sym_EQ_EQ] = ACTIONS(23),
    [anon_sym_BANG_EQ] = ACTIONS(23),
    [anon_sym_GT_EQ] = ACTIONS(23),
    [anon_sym_GT] = ACTIONS(25),
    [anon_sym_LBRACK] = ACTIONS(23),
    [sym_number] = ACTIONS(23),
    [anon_sym_DQUOTE] = ACTIONS(23),
    [anon_sym_true] = ACTIONS(25),
    [anon_sym_false] = ACTIONS(25),
    [sym_nil] = ACTIONS(25),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [6] = {
    [sym_comment] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(23),
    [sym_identifier] = ACTIONS(25),
    [anon_sym_BANG] = ACTIONS(25),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_and] = ACTIONS(25),
    [anon_sym_or] = ACTIONS(25),
    [anon_sym_PLUS] = ACTIONS(29),
    [anon_sym_STAR] = ACTIONS(31),
    [anon_sym_SLASH] = ACTIONS(33),
    [anon_sym_LT] = ACTIONS(25),
    [anon_sym_LT_EQ] = ACTIONS(23),
    [anon_sym_EQ_EQ] = ACTIONS(23),
    [anon_sym_BANG_EQ] = ACTIONS(23),
    [anon_sym_GT_EQ] = ACTIONS(23),
    [anon_sym_GT] = ACTIONS(25),
    [anon_sym_LBRACK] = ACTIONS(23),
    [sym_number] = ACTIONS(23),
    [anon_sym_DQUOTE] = ACTIONS(23),
    [anon_sym_true] = ACTIONS(25),
    [anon_sym_false] = ACTIONS(25),
    [sym_nil] = ACTIONS(25),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [7] = {
    [sym_comment] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(43),
    [sym_identifier] = ACTIONS(45),
    [anon_sym_BANG] = ACTIONS(45),
    [anon_sym_DASH] = ACTIONS(45),
    [anon_sym_and] = ACTIONS(45),
    [anon_sym_or] = ACTIONS(45),
    [anon_sym_PLUS] = ACTIONS(43),
    [anon_sym_STAR] = ACTIONS(43),
    [anon_sym_SLASH] = ACTIONS(45),
    [anon_sym_LT] = ACTIONS(45),
    [anon_sym_LT_EQ] = ACTIONS(43),
    [anon_sym_EQ_EQ] = ACTIONS(43),
    [anon_sym_BANG_EQ] = ACTIONS(43),
    [anon_sym_GT_EQ] = ACTIONS(43),
    [anon_sym_GT] = ACTIONS(45),
    [anon_sym_LBRACK] = ACTIONS(43),
    [sym_number] = ACTIONS(43),
    [anon_sym_DQUOTE] = ACTIONS(43),
    [anon_sym_true] = ACTIONS(45),
    [anon_sym_false] = ACTIONS(45),
    [sym_nil] = ACTIONS(45),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [8] = {
    [sym_comment] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(47),
    [sym_identifier] = ACTIONS(49),
    [anon_sym_BANG] = ACTIONS(49),
    [anon_sym_DASH] = ACTIONS(49),
    [anon_sym_and] = ACTIONS(49),
    [anon_sym_or] = ACTIONS(49),
    [anon_sym_PLUS] = ACTIONS(47),
    [anon_sym_STAR] = ACTIONS(47),
    [anon_sym_SLASH] = ACTIONS(49),
    [anon_sym_LT] = ACTIONS(49),
    [anon_sym_LT_EQ] = ACTIONS(47),
    [anon_sym_EQ_EQ] = ACTIONS(47),
    [anon_sym_BANG_EQ] = ACTIONS(47),
    [anon_sym_GT_EQ] = ACTIONS(47),
    [anon_sym_GT] = ACTIONS(49),
    [anon_sym_LBRACK] = ACTIONS(47),
    [sym_number] = ACTIONS(47),
    [anon_sym_DQUOTE] = ACTIONS(47),
    [anon_sym_true] = ACTIONS(49),
    [anon_sym_false] = ACTIONS(49),
    [sym_nil] = ACTIONS(49),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [9] = {
    [sym_comment] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(51),
    [sym_identifier] = ACTIONS(53),
    [anon_sym_BANG] = ACTIONS(53),
    [anon_sym_DASH] = ACTIONS(53),
    [anon_sym_and] = ACTIONS(53),
    [anon_sym_or] = ACTIONS(53),
    [anon_sym_PLUS] = ACTIONS(51),
    [anon_sym_STAR] = ACTIONS(51),
    [anon_sym_SLASH] = ACTIONS(53),
    [anon_sym_LT] = ACTIONS(53),
    [anon_sym_LT_EQ] = ACTIONS(51),
    [anon_sym_EQ_EQ] = ACTIONS(51),
    [anon_sym_BANG_EQ] = ACTIONS(51),
    [anon_sym_GT_EQ] = ACTIONS(51),
    [anon_sym_GT] = ACTIONS(53),
    [anon_sym_LBRACK] = ACTIONS(51),
    [sym_number] = ACTIONS(51),
    [anon_sym_DQUOTE] = ACTIONS(51),
    [anon_sym_true] = ACTIONS(53),
    [anon_sym_false] = ACTIONS(53),
    [sym_nil] = ACTIONS(53),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [10] = {
    [sym_comment] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(55),
    [sym_identifier] = ACTIONS(57),
    [anon_sym_BANG] = ACTIONS(57),
    [anon_sym_DASH] = ACTIONS(59),
    [anon_sym_and] = ACTIONS(39),
    [anon_sym_or] = ACTIONS(62),
    [anon_sym_PLUS] = ACTIONS(29),
    [anon_sym_STAR] = ACTIONS(31),
    [anon_sym_SLASH] = ACTIONS(33),
    [anon_sym_LT] = ACTIONS(35),
    [anon_sym_LT_EQ] = ACTIONS(37),
    [anon_sym_EQ_EQ] = ACTIONS(41),
    [anon_sym_BANG_EQ] = ACTIONS(41),
    [anon_sym_GT_EQ] = ACTIONS(37),
    [anon_sym_GT] = ACTIONS(35),
    [anon_sym_LBRACK] = ACTIONS(55),
    [sym_number] = ACTIONS(55),
    [anon_sym_DQUOTE] = ACTIONS(55),
    [anon_sym_true] = ACTIONS(57),
    [anon_sym_false] = ACTIONS(57),
    [sym_nil] = ACTIONS(57),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [11] = {
    [sym_comment] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(64),
    [sym_identifier] = ACTIONS(66),
    [anon_sym_BANG] = ACTIONS(66),
    [anon_sym_DASH] = ACTIONS(66),
    [anon_sym_and] = ACTIONS(66),
    [anon_sym_or] = ACTIONS(66),
    [anon_sym_PLUS] = ACTIONS(64),
    [anon_sym_STAR] = ACTIONS(64),
    [anon_sym_SLASH] = ACTIONS(66),
    [anon_sym_LT] = ACTIONS(66),
    [anon_sym_LT_EQ] = ACTIONS(64),
    [anon_sym_EQ_EQ] = ACTIONS(64),
    [anon_sym_BANG_EQ] = ACTIONS(64),
    [anon_sym_GT_EQ] = ACTIONS(64),
    [anon_sym_GT] = ACTIONS(66),
    [anon_sym_LBRACK] = ACTIONS(64),
    [sym_number] = ACTIONS(64),
    [anon_sym_DQUOTE] = ACTIONS(64),
    [anon_sym_true] = ACTIONS(66),
    [anon_sym_false] = ACTIONS(66),
    [sym_nil] = ACTIONS(66),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [12] = {
    [sym_comment] = STATE(12),
    [ts_builtin_sym_end] = ACTIONS(23),
    [sym_identifier] = ACTIONS(25),
    [anon_sym_BANG] = ACTIONS(25),
    [anon_sym_DASH] = ACTIONS(25),
    [anon_sym_and] = ACTIONS(25),
    [anon_sym_or] = ACTIONS(25),
    [anon_sym_PLUS] = ACTIONS(23),
    [anon_sym_STAR] = ACTIONS(23),
    [anon_sym_SLASH] = ACTIONS(25),
    [anon_sym_LT] = ACTIONS(25),
    [anon_sym_LT_EQ] = ACTIONS(23),
    [anon_sym_EQ_EQ] = ACTIONS(23),
    [anon_sym_BANG_EQ] = ACTIONS(23),
    [anon_sym_GT_EQ] = ACTIONS(23),
    [anon_sym_GT] = ACTIONS(25),
    [anon_sym_LBRACK] = ACTIONS(23),
    [sym_number] = ACTIONS(23),
    [anon_sym_DQUOTE] = ACTIONS(23),
    [anon_sym_true] = ACTIONS(25),
    [anon_sym_false] = ACTIONS(25),
    [sym_nil] = ACTIONS(25),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [13] = {
    [sym_comment] = STATE(13),
    [ts_builtin_sym_end] = ACTIONS(68),
    [sym_identifier] = ACTIONS(70),
    [anon_sym_BANG] = ACTIONS(70),
    [anon_sym_DASH] = ACTIONS(70),
    [anon_sym_and] = ACTIONS(70),
    [anon_sym_or] = ACTIONS(70),
    [anon_sym_PLUS] = ACTIONS(68),
    [anon_sym_STAR] = ACTIONS(68),
    [anon_sym_SLASH] = ACTIONS(70),
    [anon_sym_LT] = ACTIONS(70),
    [anon_sym_LT_EQ] = ACTIONS(68),
    [anon_sym_EQ_EQ] = ACTIONS(68),
    [anon_sym_BANG_EQ] = ACTIONS(68),
    [anon_sym_GT_EQ] = ACTIONS(68),
    [anon_sym_GT] = ACTIONS(70),
    [anon_sym_LBRACK] = ACTIONS(68),
    [sym_number] = ACTIONS(68),
    [anon_sym_DQUOTE] = ACTIONS(68),
    [anon_sym_true] = ACTIONS(70),
    [anon_sym_false] = ACTIONS(70),
    [sym_nil] = ACTIONS(70),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [14] = {
    [sym_comment] = STATE(14),
    [ts_builtin_sym_end] = ACTIONS(72),
    [sym_identifier] = ACTIONS(74),
    [anon_sym_BANG] = ACTIONS(74),
    [anon_sym_DASH] = ACTIONS(74),
    [anon_sym_and] = ACTIONS(74),
    [anon_sym_or] = ACTIONS(74),
    [anon_sym_PLUS] = ACTIONS(72),
    [anon_sym_STAR] = ACTIONS(72),
    [anon_sym_SLASH] = ACTIONS(74),
    [anon_sym_LT] = ACTIONS(74),
    [anon_sym_LT_EQ] = ACTIONS(72),
    [anon_sym_EQ_EQ] = ACTIONS(72),
    [anon_sym_BANG_EQ] = ACTIONS(72),
    [anon_sym_GT_EQ] = ACTIONS(72),
    [anon_sym_GT] = ACTIONS(74),
    [anon_sym_LBRACK] = ACTIONS(72),
    [sym_number] = ACTIONS(72),
    [anon_sym_DQUOTE] = ACTIONS(72),
    [anon_sym_true] = ACTIONS(74),
    [anon_sym_false] = ACTIONS(74),
    [sym_nil] = ACTIONS(74),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [15] = {
    [sym_comment] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(76),
    [sym_identifier] = ACTIONS(78),
    [anon_sym_BANG] = ACTIONS(78),
    [anon_sym_DASH] = ACTIONS(78),
    [anon_sym_and] = ACTIONS(78),
    [anon_sym_or] = ACTIONS(78),
    [anon_sym_PLUS] = ACTIONS(76),
    [anon_sym_STAR] = ACTIONS(76),
    [anon_sym_SLASH] = ACTIONS(78),
    [anon_sym_LT] = ACTIONS(78),
    [anon_sym_LT_EQ] = ACTIONS(76),
    [anon_sym_EQ_EQ] = ACTIONS(76),
    [anon_sym_BANG_EQ] = ACTIONS(76),
    [anon_sym_GT_EQ] = ACTIONS(76),
    [anon_sym_GT] = ACTIONS(78),
    [anon_sym_LBRACK] = ACTIONS(76),
    [sym_number] = ACTIONS(76),
    [anon_sym_DQUOTE] = ACTIONS(76),
    [anon_sym_true] = ACTIONS(78),
    [anon_sym_false] = ACTIONS(78),
    [sym_nil] = ACTIONS(78),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [16] = {
    [sym_comment] = STATE(16),
    [ts_builtin_sym_end] = ACTIONS(80),
    [sym_identifier] = ACTIONS(82),
    [anon_sym_BANG] = ACTIONS(82),
    [anon_sym_DASH] = ACTIONS(82),
    [anon_sym_and] = ACTIONS(82),
    [anon_sym_or] = ACTIONS(82),
    [anon_sym_PLUS] = ACTIONS(80),
    [anon_sym_STAR] = ACTIONS(80),
    [anon_sym_SLASH] = ACTIONS(82),
    [anon_sym_LT] = ACTIONS(82),
    [anon_sym_LT_EQ] = ACTIONS(80),
    [anon_sym_EQ_EQ] = ACTIONS(80),
    [anon_sym_BANG_EQ] = ACTIONS(80),
    [anon_sym_GT_EQ] = ACTIONS(80),
    [anon_sym_GT] = ACTIONS(82),
    [anon_sym_LBRACK] = ACTIONS(80),
    [sym_number] = ACTIONS(80),
    [anon_sym_DQUOTE] = ACTIONS(80),
    [anon_sym_true] = ACTIONS(82),
    [anon_sym_false] = ACTIONS(82),
    [sym_nil] = ACTIONS(82),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [17] = {
    [sym_comment] = STATE(17),
    [ts_builtin_sym_end] = ACTIONS(84),
    [sym_identifier] = ACTIONS(86),
    [anon_sym_BANG] = ACTIONS(86),
    [anon_sym_DASH] = ACTIONS(86),
    [anon_sym_and] = ACTIONS(86),
    [anon_sym_or] = ACTIONS(86),
    [anon_sym_PLUS] = ACTIONS(84),
    [anon_sym_STAR] = ACTIONS(84),
    [anon_sym_SLASH] = ACTIONS(86),
    [anon_sym_LT] = ACTIONS(86),
    [anon_sym_LT_EQ] = ACTIONS(84),
    [anon_sym_EQ_EQ] = ACTIONS(84),
    [anon_sym_BANG_EQ] = ACTIONS(84),
    [anon_sym_GT_EQ] = ACTIONS(84),
    [anon_sym_GT] = ACTIONS(86),
    [anon_sym_LBRACK] = ACTIONS(84),
    [sym_number] = ACTIONS(84),
    [anon_sym_DQUOTE] = ACTIONS(84),
    [anon_sym_true] = ACTIONS(86),
    [anon_sym_false] = ACTIONS(86),
    [sym_nil] = ACTIONS(86),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [18] = {
    [sym_comment] = STATE(18),
    [ts_builtin_sym_end] = ACTIONS(88),
    [sym_identifier] = ACTIONS(90),
    [anon_sym_BANG] = ACTIONS(90),
    [anon_sym_DASH] = ACTIONS(90),
    [anon_sym_and] = ACTIONS(90),
    [anon_sym_or] = ACTIONS(90),
    [anon_sym_PLUS] = ACTIONS(88),
    [anon_sym_STAR] = ACTIONS(88),
    [anon_sym_SLASH] = ACTIONS(90),
    [anon_sym_LT] = ACTIONS(90),
    [anon_sym_LT_EQ] = ACTIONS(88),
    [anon_sym_EQ_EQ] = ACTIONS(88),
    [anon_sym_BANG_EQ] = ACTIONS(88),
    [anon_sym_GT_EQ] = ACTIONS(88),
    [anon_sym_GT] = ACTIONS(90),
    [anon_sym_LBRACK] = ACTIONS(88),
    [sym_number] = ACTIONS(88),
    [anon_sym_DQUOTE] = ACTIONS(88),
    [anon_sym_true] = ACTIONS(90),
    [anon_sym_false] = ACTIONS(90),
    [sym_nil] = ACTIONS(90),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(11), 1,
      anon_sym_BANG,
    ACTIONS(13), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      sym_number,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(92), 1,
      ts_builtin_sym_end,
    STATE(10), 1,
      sym__expression,
    STATE(19), 1,
      sym_comment,
    STATE(22), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(7), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(7), 2,
      sym_string,
      sym_boolean,
    STATE(11), 4,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [49] = 14,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(11), 1,
      anon_sym_BANG,
    ACTIONS(13), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      sym_number,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(94), 1,
      ts_builtin_sym_end,
    STATE(10), 1,
      sym__expression,
    STATE(20), 1,
      sym_comment,
    STATE(22), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(7), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(7), 2,
      sym_string,
      sym_boolean,
    STATE(11), 4,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [98] = 14,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(11), 1,
      anon_sym_BANG,
    ACTIONS(13), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      sym_number,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(94), 1,
      ts_builtin_sym_end,
    STATE(10), 1,
      sym__expression,
    STATE(19), 1,
      aux_sym_source_file_repeat1,
    STATE(21), 1,
      sym_comment,
    ACTIONS(7), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(7), 2,
      sym_string,
      sym_boolean,
    STATE(11), 4,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [147] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(96), 1,
      ts_builtin_sym_end,
    ACTIONS(101), 1,
      anon_sym_BANG,
    ACTIONS(104), 1,
      anon_sym_DASH,
    ACTIONS(107), 1,
      anon_sym_LBRACK,
    ACTIONS(110), 1,
      sym_number,
    ACTIONS(113), 1,
      anon_sym_DQUOTE,
    STATE(10), 1,
      sym__expression,
    ACTIONS(98), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(116), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(7), 2,
      sym_string,
      sym_boolean,
    STATE(22), 2,
      sym_comment,
      aux_sym_source_file_repeat1,
    STATE(11), 4,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [194] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(121), 1,
      anon_sym_BANG,
    ACTIONS(123), 1,
      anon_sym_DASH,
    ACTIONS(125), 1,
      anon_sym_LBRACK,
    ACTIONS(127), 1,
      anon_sym_RBRACK,
    ACTIONS(129), 1,
      sym_number,
    ACTIONS(131), 1,
      anon_sym_DQUOTE,
    STATE(23), 1,
      sym_comment,
    STATE(59), 1,
      sym__expression,
    ACTIONS(119), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(133), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(48), 2,
      sym_string,
      sym_boolean,
    STATE(50), 4,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [240] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(121), 1,
      anon_sym_BANG,
    ACTIONS(123), 1,
      anon_sym_DASH,
    ACTIONS(125), 1,
      anon_sym_LBRACK,
    ACTIONS(129), 1,
      sym_number,
    ACTIONS(131), 1,
      anon_sym_DQUOTE,
    ACTIONS(135), 1,
      anon_sym_RBRACK,
    STATE(24), 1,
      sym_comment,
    STATE(59), 1,
      sym__expression,
    ACTIONS(119), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(133), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(48), 2,
      sym_string,
      sym_boolean,
    STATE(50), 4,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [286] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(121), 1,
      anon_sym_BANG,
    ACTIONS(123), 1,
      anon_sym_DASH,
    ACTIONS(125), 1,
      anon_sym_LBRACK,
    ACTIONS(129), 1,
      sym_number,
    ACTIONS(131), 1,
      anon_sym_DQUOTE,
    ACTIONS(137), 1,
      anon_sym_RBRACK,
    STATE(25), 1,
      sym_comment,
    STATE(44), 1,
      sym__expression,
    ACTIONS(119), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(133), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(48), 2,
      sym_string,
      sym_boolean,
    STATE(50), 4,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [332] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(121), 1,
      anon_sym_BANG,
    ACTIONS(123), 1,
      anon_sym_DASH,
    ACTIONS(125), 1,
      anon_sym_LBRACK,
    ACTIONS(129), 1,
      sym_number,
    ACTIONS(131), 1,
      anon_sym_DQUOTE,
    ACTIONS(139), 1,
      anon_sym_RBRACK,
    STATE(26), 1,
      sym_comment,
    STATE(45), 1,
      sym__expression,
    ACTIONS(119), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(133), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(48), 2,
      sym_string,
      sym_boolean,
    STATE(50), 4,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [378] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(121), 1,
      anon_sym_BANG,
    ACTIONS(123), 1,
      anon_sym_DASH,
    ACTIONS(125), 1,
      anon_sym_LBRACK,
    ACTIONS(129), 1,
      sym_number,
    ACTIONS(131), 1,
      anon_sym_DQUOTE,
    ACTIONS(141), 1,
      anon_sym_RBRACK,
    STATE(27), 1,
      sym_comment,
    STATE(59), 1,
      sym__expression,
    ACTIONS(119), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(133), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(48), 2,
      sym_string,
      sym_boolean,
    STATE(50), 4,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [424] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(121), 1,
      anon_sym_BANG,
    ACTIONS(123), 1,
      anon_sym_DASH,
    ACTIONS(125), 1,
      anon_sym_LBRACK,
    ACTIONS(129), 1,
      sym_number,
    ACTIONS(131), 1,
      anon_sym_DQUOTE,
    ACTIONS(143), 1,
      anon_sym_RBRACK,
    STATE(28), 1,
      sym_comment,
    STATE(59), 1,
      sym__expression,
    ACTIONS(119), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(133), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(48), 2,
      sym_string,
      sym_boolean,
    STATE(50), 4,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [470] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(121), 1,
      anon_sym_BANG,
    ACTIONS(123), 1,
      anon_sym_DASH,
    ACTIONS(125), 1,
      anon_sym_LBRACK,
    ACTIONS(129), 1,
      sym_number,
    ACTIONS(131), 1,
      anon_sym_DQUOTE,
    STATE(29), 1,
      sym_comment,
    STATE(62), 1,
      sym__expression,
    ACTIONS(119), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(133), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(48), 2,
      sym_string,
      sym_boolean,
    STATE(50), 4,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [513] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(121), 1,
      anon_sym_BANG,
    ACTIONS(123), 1,
      anon_sym_DASH,
    ACTIONS(125), 1,
      anon_sym_LBRACK,
    ACTIONS(129), 1,
      sym_number,
    ACTIONS(131), 1,
      anon_sym_DQUOTE,
    STATE(30), 1,
      sym_comment,
    STATE(60), 1,
      sym__expression,
    ACTIONS(119), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(133), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(48), 2,
      sym_string,
      sym_boolean,
    STATE(50), 4,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [556] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(11), 1,
      anon_sym_BANG,
    ACTIONS(13), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      sym_number,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    STATE(4), 1,
      sym__expression,
    STATE(31), 1,
      sym_comment,
    ACTIONS(7), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(7), 2,
      sym_string,
      sym_boolean,
    STATE(11), 4,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [599] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(11), 1,
      anon_sym_BANG,
    ACTIONS(13), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      sym_number,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    STATE(3), 1,
      sym__expression,
    STATE(32), 1,
      sym_comment,
    ACTIONS(7), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(7), 2,
      sym_string,
      sym_boolean,
    STATE(11), 4,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [642] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(11), 1,
      anon_sym_BANG,
    ACTIONS(13), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      sym_number,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    STATE(12), 1,
      sym__expression,
    STATE(33), 1,
      sym_comment,
    ACTIONS(7), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(7), 2,
      sym_string,
      sym_boolean,
    STATE(11), 4,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [685] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(11), 1,
      anon_sym_BANG,
    ACTIONS(13), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      sym_number,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    STATE(6), 1,
      sym__expression,
    STATE(34), 1,
      sym_comment,
    ACTIONS(7), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(7), 2,
      sym_string,
      sym_boolean,
    STATE(11), 4,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [728] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(11), 1,
      anon_sym_BANG,
    ACTIONS(13), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      sym_number,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    STATE(2), 1,
      sym__expression,
    STATE(35), 1,
      sym_comment,
    ACTIONS(7), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(7), 2,
      sym_string,
      sym_boolean,
    STATE(11), 4,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [771] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(11), 1,
      anon_sym_BANG,
    ACTIONS(13), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      sym_number,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    STATE(15), 1,
      sym__expression,
    STATE(36), 1,
      sym_comment,
    ACTIONS(7), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(7), 2,
      sym_string,
      sym_boolean,
    STATE(11), 4,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [814] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(121), 1,
      anon_sym_BANG,
    ACTIONS(123), 1,
      anon_sym_DASH,
    ACTIONS(125), 1,
      anon_sym_LBRACK,
    ACTIONS(129), 1,
      sym_number,
    ACTIONS(131), 1,
      anon_sym_DQUOTE,
    STATE(37), 1,
      sym_comment,
    STATE(51), 1,
      sym__expression,
    ACTIONS(119), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(133), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(48), 2,
      sym_string,
      sym_boolean,
    STATE(50), 4,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [857] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(11), 1,
      anon_sym_BANG,
    ACTIONS(13), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      sym_number,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    STATE(5), 1,
      sym__expression,
    STATE(38), 1,
      sym_comment,
    ACTIONS(7), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(7), 2,
      sym_string,
      sym_boolean,
    STATE(11), 4,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [900] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(121), 1,
      anon_sym_BANG,
    ACTIONS(123), 1,
      anon_sym_DASH,
    ACTIONS(125), 1,
      anon_sym_LBRACK,
    ACTIONS(129), 1,
      sym_number,
    ACTIONS(131), 1,
      anon_sym_DQUOTE,
    STATE(39), 1,
      sym_comment,
    STATE(56), 1,
      sym__expression,
    ACTIONS(119), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(133), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(48), 2,
      sym_string,
      sym_boolean,
    STATE(50), 4,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [943] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(121), 1,
      anon_sym_BANG,
    ACTIONS(123), 1,
      anon_sym_DASH,
    ACTIONS(125), 1,
      anon_sym_LBRACK,
    ACTIONS(129), 1,
      sym_number,
    ACTIONS(131), 1,
      anon_sym_DQUOTE,
    STATE(40), 1,
      sym_comment,
    STATE(46), 1,
      sym__expression,
    ACTIONS(119), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(133), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(48), 2,
      sym_string,
      sym_boolean,
    STATE(50), 4,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [986] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(121), 1,
      anon_sym_BANG,
    ACTIONS(123), 1,
      anon_sym_DASH,
    ACTIONS(125), 1,
      anon_sym_LBRACK,
    ACTIONS(129), 1,
      sym_number,
    ACTIONS(131), 1,
      anon_sym_DQUOTE,
    STATE(41), 1,
      sym_comment,
    STATE(61), 1,
      sym__expression,
    ACTIONS(119), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(133), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(48), 2,
      sym_string,
      sym_boolean,
    STATE(50), 4,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [1029] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(121), 1,
      anon_sym_BANG,
    ACTIONS(123), 1,
      anon_sym_DASH,
    ACTIONS(125), 1,
      anon_sym_LBRACK,
    ACTIONS(129), 1,
      sym_number,
    ACTIONS(131), 1,
      anon_sym_DQUOTE,
    STATE(42), 1,
      sym_comment,
    STATE(59), 1,
      sym__expression,
    ACTIONS(119), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(133), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(48), 2,
      sym_string,
      sym_boolean,
    STATE(50), 4,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [1072] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(121), 1,
      anon_sym_BANG,
    ACTIONS(123), 1,
      anon_sym_DASH,
    ACTIONS(125), 1,
      anon_sym_LBRACK,
    ACTIONS(129), 1,
      sym_number,
    ACTIONS(131), 1,
      anon_sym_DQUOTE,
    STATE(43), 1,
      sym_comment,
    STATE(47), 1,
      sym__expression,
    ACTIONS(119), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(133), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(48), 2,
      sym_string,
      sym_boolean,
    STATE(50), 4,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [1115] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(147), 1,
      anon_sym_and,
    ACTIONS(149), 1,
      anon_sym_or,
    ACTIONS(151), 1,
      anon_sym_STAR,
    ACTIONS(153), 1,
      anon_sym_SLASH,
    ACTIONS(161), 1,
      anon_sym_COMMA,
    ACTIONS(163), 1,
      anon_sym_RBRACK,
    STATE(44), 1,
      sym_comment,
    STATE(68), 1,
      aux_sym_array_repeat1,
    ACTIONS(145), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(155), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(157), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(159), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1159] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(147), 1,
      anon_sym_and,
    ACTIONS(149), 1,
      anon_sym_or,
    ACTIONS(151), 1,
      anon_sym_STAR,
    ACTIONS(153), 1,
      anon_sym_SLASH,
    ACTIONS(165), 1,
      anon_sym_COMMA,
    ACTIONS(167), 1,
      anon_sym_RBRACK,
    STATE(45), 1,
      sym_comment,
    STATE(70), 1,
      aux_sym_array_repeat1,
    ACTIONS(145), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(155), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(157), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(159), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1203] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(151), 1,
      anon_sym_STAR,
    ACTIONS(153), 1,
      anon_sym_SLASH,
    STATE(46), 1,
      sym_comment,
    ACTIONS(25), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(145), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(23), 8,
      anon_sym_and,
      anon_sym_or,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1234] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(151), 1,
      anon_sym_STAR,
    ACTIONS(153), 1,
      anon_sym_SLASH,
    STATE(47), 1,
      sym_comment,
    ACTIONS(25), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(23), 10,
      anon_sym_DASH,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1263] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(48), 1,
      sym_comment,
    ACTIONS(45), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(43), 11,
      anon_sym_DASH,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1288] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(49), 1,
      sym_comment,
    ACTIONS(53), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(51), 11,
      anon_sym_DASH,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1313] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(50), 1,
      sym_comment,
    ACTIONS(66), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(64), 11,
      anon_sym_DASH,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1338] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(51), 1,
      sym_comment,
    ACTIONS(78), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(76), 11,
      anon_sym_DASH,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1363] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(52), 1,
      sym_comment,
    ACTIONS(82), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(80), 11,
      anon_sym_DASH,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1388] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(53), 1,
      sym_comment,
    ACTIONS(86), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(84), 11,
      anon_sym_DASH,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1413] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(54), 1,
      sym_comment,
    ACTIONS(70), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(68), 11,
      anon_sym_DASH,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1438] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(55), 1,
      sym_comment,
    ACTIONS(90), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(88), 11,
      anon_sym_DASH,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1463] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(151), 1,
      anon_sym_STAR,
    ACTIONS(153), 1,
      anon_sym_SLASH,
    STATE(56), 1,
      sym_comment,
    ACTIONS(145), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(155), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(157), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(23), 6,
      anon_sym_and,
      anon_sym_or,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1496] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(57), 1,
      sym_comment,
    ACTIONS(74), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(72), 11,
      anon_sym_DASH,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1521] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(58), 1,
      sym_comment,
    ACTIONS(49), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(47), 11,
      anon_sym_DASH,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1546] = 11,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(147), 1,
      anon_sym_and,
    ACTIONS(149), 1,
      anon_sym_or,
    ACTIONS(151), 1,
      anon_sym_STAR,
    ACTIONS(153), 1,
      anon_sym_SLASH,
    STATE(59), 1,
      sym_comment,
    ACTIONS(145), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(155), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(157), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(159), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(169), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1585] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(151), 1,
      anon_sym_STAR,
    ACTIONS(153), 1,
      anon_sym_SLASH,
    STATE(60), 1,
      sym_comment,
    ACTIONS(145), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(155), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(157), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(159), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(23), 4,
      anon_sym_and,
      anon_sym_or,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1620] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(147), 1,
      anon_sym_and,
    ACTIONS(151), 1,
      anon_sym_STAR,
    ACTIONS(153), 1,
      anon_sym_SLASH,
    STATE(61), 1,
      sym_comment,
    ACTIONS(145), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(155), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(157), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(159), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(23), 3,
      anon_sym_or,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1657] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(62), 1,
      sym_comment,
    ACTIONS(25), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(23), 11,
      anon_sym_DASH,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1682] = 4,
    ACTIONS(171), 1,
      anon_sym_DQUOTE,
    ACTIONS(176), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(173), 2,
      sym_unescaped_double_string_fragment,
      sym_escape_sequence,
    STATE(63), 2,
      sym_comment,
      aux_sym_string_repeat1,
  [1697] = 5,
    ACTIONS(176), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(178), 1,
      anon_sym_DQUOTE,
    STATE(63), 1,
      aux_sym_string_repeat1,
    STATE(64), 1,
      sym_comment,
    ACTIONS(180), 2,
      sym_unescaped_double_string_fragment,
      sym_escape_sequence,
  [1714] = 5,
    ACTIONS(176), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(182), 1,
      anon_sym_DQUOTE,
    STATE(65), 1,
      sym_comment,
    STATE(66), 1,
      aux_sym_string_repeat1,
    ACTIONS(180), 2,
      sym_unescaped_double_string_fragment,
      sym_escape_sequence,
  [1731] = 5,
    ACTIONS(176), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(184), 1,
      anon_sym_DQUOTE,
    STATE(63), 1,
      aux_sym_string_repeat1,
    STATE(66), 1,
      sym_comment,
    ACTIONS(180), 2,
      sym_unescaped_double_string_fragment,
      sym_escape_sequence,
  [1748] = 5,
    ACTIONS(176), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(186), 1,
      anon_sym_DQUOTE,
    STATE(64), 1,
      aux_sym_string_repeat1,
    STATE(67), 1,
      sym_comment,
    ACTIONS(180), 2,
      sym_unescaped_double_string_fragment,
      sym_escape_sequence,
  [1765] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(141), 1,
      anon_sym_RBRACK,
    ACTIONS(188), 1,
      anon_sym_COMMA,
    STATE(68), 1,
      sym_comment,
    STATE(71), 1,
      aux_sym_array_repeat1,
  [1781] = 4,
    ACTIONS(176), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(190), 1,
      anon_sym_DQUOTE,
    STATE(69), 1,
      sym_comment,
    ACTIONS(192), 2,
      sym_unescaped_double_string_fragment,
      sym_escape_sequence,
  [1795] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(143), 1,
      anon_sym_RBRACK,
    ACTIONS(194), 1,
      anon_sym_COMMA,
    STATE(70), 1,
      sym_comment,
    STATE(71), 1,
      aux_sym_array_repeat1,
  [1811] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(169), 1,
      anon_sym_RBRACK,
    ACTIONS(196), 1,
      anon_sym_COMMA,
    STATE(71), 2,
      sym_comment,
      aux_sym_array_repeat1,
  [1825] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(199), 1,
      ts_builtin_sym_end,
    STATE(72), 1,
      sym_comment,
  [1835] = 3,
    ACTIONS(176), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(201), 1,
      aux_sym_comment_token1,
    STATE(73), 1,
      sym_comment,
  [1845] = 1,
    ACTIONS(203), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(19)] = 0,
  [SMALL_STATE(20)] = 49,
  [SMALL_STATE(21)] = 98,
  [SMALL_STATE(22)] = 147,
  [SMALL_STATE(23)] = 194,
  [SMALL_STATE(24)] = 240,
  [SMALL_STATE(25)] = 286,
  [SMALL_STATE(26)] = 332,
  [SMALL_STATE(27)] = 378,
  [SMALL_STATE(28)] = 424,
  [SMALL_STATE(29)] = 470,
  [SMALL_STATE(30)] = 513,
  [SMALL_STATE(31)] = 556,
  [SMALL_STATE(32)] = 599,
  [SMALL_STATE(33)] = 642,
  [SMALL_STATE(34)] = 685,
  [SMALL_STATE(35)] = 728,
  [SMALL_STATE(36)] = 771,
  [SMALL_STATE(37)] = 814,
  [SMALL_STATE(38)] = 857,
  [SMALL_STATE(39)] = 900,
  [SMALL_STATE(40)] = 943,
  [SMALL_STATE(41)] = 986,
  [SMALL_STATE(42)] = 1029,
  [SMALL_STATE(43)] = 1072,
  [SMALL_STATE(44)] = 1115,
  [SMALL_STATE(45)] = 1159,
  [SMALL_STATE(46)] = 1203,
  [SMALL_STATE(47)] = 1234,
  [SMALL_STATE(48)] = 1263,
  [SMALL_STATE(49)] = 1288,
  [SMALL_STATE(50)] = 1313,
  [SMALL_STATE(51)] = 1338,
  [SMALL_STATE(52)] = 1363,
  [SMALL_STATE(53)] = 1388,
  [SMALL_STATE(54)] = 1413,
  [SMALL_STATE(55)] = 1438,
  [SMALL_STATE(56)] = 1463,
  [SMALL_STATE(57)] = 1496,
  [SMALL_STATE(58)] = 1521,
  [SMALL_STATE(59)] = 1546,
  [SMALL_STATE(60)] = 1585,
  [SMALL_STATE(61)] = 1620,
  [SMALL_STATE(62)] = 1657,
  [SMALL_STATE(63)] = 1682,
  [SMALL_STATE(64)] = 1697,
  [SMALL_STATE(65)] = 1714,
  [SMALL_STATE(66)] = 1731,
  [SMALL_STATE(67)] = 1748,
  [SMALL_STATE(68)] = 1765,
  [SMALL_STATE(69)] = 1781,
  [SMALL_STATE(70)] = 1795,
  [SMALL_STATE(71)] = 1811,
  [SMALL_STATE(72)] = 1825,
  [SMALL_STATE(73)] = 1835,
  [SMALL_STATE(74)] = 1845,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, .production_id = 2),
  [25] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, .production_id = 2),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__primary, 1),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__primary, 1),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1),
  [59] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1), SHIFT(38),
  [62] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 5),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 5),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 3),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expression, 2, .production_id = 1),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_expression, 2, .production_id = 1),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 2),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 4),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 4),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [98] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(7),
  [101] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(36),
  [104] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(36),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(26),
  [110] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(7),
  [113] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(67),
  [116] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(9),
  [119] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [123] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [133] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [153] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [155] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2),
  [173] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(69),
  [176] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [178] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [182] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [184] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [186] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 1),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 1),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [196] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(42),
  [199] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [201] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_lx(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
