#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 81
#define LARGE_STATE_COUNT 24
#define SYMBOL_COUNT 43
#define ALIAS_COUNT 0
#define TOKEN_COUNT 30
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 3

enum {
  sym_identifier = 1,
  sym_shell_bang = 2,
  anon_sym_LPAREN = 3,
  anon_sym_RPAREN = 4,
  anon_sym_BANG = 5,
  anon_sym_DASH = 6,
  anon_sym_and = 7,
  anon_sym_or = 8,
  anon_sym_PLUS = 9,
  anon_sym_STAR = 10,
  anon_sym_SLASH = 11,
  anon_sym_LT = 12,
  anon_sym_LT_EQ = 13,
  anon_sym_EQ_EQ = 14,
  anon_sym_BANG_EQ = 15,
  anon_sym_GT_EQ = 16,
  anon_sym_GT = 17,
  anon_sym_LBRACK = 18,
  anon_sym_COMMA = 19,
  anon_sym_RBRACK = 20,
  sym_number = 21,
  anon_sym_DQUOTE = 22,
  sym_unescaped_double_string_fragment = 23,
  sym_escape_sequence = 24,
  anon_sym_true = 25,
  anon_sym_false = 26,
  sym_nil = 27,
  anon_sym_SLASH_SLASH = 28,
  aux_sym_comment_token1 = 29,
  sym_source_file = 30,
  sym__expression = 31,
  sym_parenthesized_expression = 32,
  sym_unary_expression = 33,
  sym_binary_expression = 34,
  sym_array = 35,
  sym__primary = 36,
  sym_string = 37,
  sym_boolean = 38,
  sym_comment = 39,
  aux_sym_source_file_repeat1 = 40,
  aux_sym_array_repeat1 = 41,
  aux_sym_string_repeat1 = 42,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_shell_bang] = "shell_bang",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_BANG] = "!",
  [anon_sym_DASH] = "-",
  [anon_sym_and] = "and",
  [anon_sym_or] = "or",
  [anon_sym_PLUS] = "+",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_LT] = "<",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_GT] = ">",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [sym_number] = "number",
  [anon_sym_DQUOTE] = "\"",
  [sym_unescaped_double_string_fragment] = "string_fragment",
  [sym_escape_sequence] = "escape_sequence",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_nil] = "nil",
  [anon_sym_SLASH_SLASH] = "//",
  [aux_sym_comment_token1] = "comment_token1",
  [sym_source_file] = "source_file",
  [sym__expression] = "_expression",
  [sym_parenthesized_expression] = "parenthesized_expression",
  [sym_unary_expression] = "unary_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_array] = "array",
  [sym__primary] = "_primary",
  [sym_string] = "string",
  [sym_boolean] = "boolean",
  [sym_comment] = "comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_array_repeat1] = "array_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_shell_bang] = sym_shell_bang,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_and] = anon_sym_and,
  [anon_sym_or] = anon_sym_or,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_number] = sym_number,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym_unescaped_double_string_fragment] = sym_unescaped_double_string_fragment,
  [sym_escape_sequence] = sym_escape_sequence,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_nil] = sym_nil,
  [anon_sym_SLASH_SLASH] = anon_sym_SLASH_SLASH,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [sym_source_file] = sym_source_file,
  [sym__expression] = sym__expression,
  [sym_parenthesized_expression] = sym_parenthesized_expression,
  [sym_unary_expression] = sym_unary_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_array] = sym_array,
  [sym__primary] = sym__primary,
  [sym_string] = sym_string,
  [sym_boolean] = sym_boolean,
  [sym_comment] = sym_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_shell_bang] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_or] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_unescaped_double_string_fragment] = {
    .visible = true,
    .named = true,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_nil] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_parenthesized_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym__primary] = {
    .visible = false,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_left = 1,
  field_operator = 2,
  field_right = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_left] = "left",
  [field_operator] = "operator",
  [field_right] = "right",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_operator, 0},
    {field_right, 1},
  [2] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 24,
  [26] = 26,
  [27] = 27,
  [28] = 27,
  [29] = 26,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 32,
  [34] = 30,
  [35] = 31,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 38,
  [41] = 36,
  [42] = 42,
  [43] = 42,
  [44] = 39,
  [45] = 45,
  [46] = 37,
  [47] = 47,
  [48] = 2,
  [49] = 9,
  [50] = 3,
  [51] = 17,
  [52] = 18,
  [53] = 16,
  [54] = 47,
  [55] = 7,
  [56] = 19,
  [57] = 5,
  [58] = 15,
  [59] = 10,
  [60] = 8,
  [61] = 14,
  [62] = 6,
  [63] = 4,
  [64] = 13,
  [65] = 12,
  [66] = 66,
  [67] = 67,
  [68] = 67,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 69,
  [73] = 71,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 75,
  [78] = 78,
  [79] = 79,
  [80] = 80,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(9);
      if (lookahead == '!') ADVANCE(13);
      if (lookahead == '"') ADVANCE(31);
      if (lookahead == '#') ADVANCE(1);
      if (lookahead == '(') ADVANCE(11);
      if (lookahead == ')') ADVANCE(12);
      if (lookahead == '*') ADVANCE(17);
      if (lookahead == '+') ADVANCE(16);
      if (lookahead == ',') ADVANCE(26);
      if (lookahead == '-') ADVANCE(15);
      if (lookahead == '/') ADVANCE(18);
      if (lookahead == '<') ADVANCE(19);
      if (lookahead == '=') ADVANCE(5);
      if (lookahead == '>') ADVANCE(24);
      if (lookahead == '[') ADVANCE(25);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead == ']') ADVANCE(27);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(8)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(10);
      END_STATE();
    case 2:
      if (lookahead == '!') ADVANCE(4);
      if (lookahead == ')') ADVANCE(12);
      if (lookahead == '*') ADVANCE(17);
      if (lookahead == '+') ADVANCE(16);
      if (lookahead == ',') ADVANCE(26);
      if (lookahead == '-') ADVANCE(14);
      if (lookahead == '/') ADVANCE(18);
      if (lookahead == '<') ADVANCE(19);
      if (lookahead == '=') ADVANCE(5);
      if (lookahead == '>') ADVANCE(24);
      if (lookahead == ']') ADVANCE(27);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(31);
      if (lookahead == '/') ADVANCE(33);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0) ADVANCE(34);
      END_STATE();
    case 4:
      if (lookahead == '=') ADVANCE(22);
      END_STATE();
    case 5:
      if (lookahead == '=') ADVANCE(21);
      END_STATE();
    case 6:
      if (lookahead == '"' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't') ADVANCE(35);
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 8:
      if (eof) ADVANCE(9);
      if (lookahead == '!') ADVANCE(13);
      if (lookahead == '"') ADVANCE(31);
      if (lookahead == '(') ADVANCE(11);
      if (lookahead == ')') ADVANCE(12);
      if (lookahead == '*') ADVANCE(17);
      if (lookahead == '+') ADVANCE(16);
      if (lookahead == ',') ADVANCE(26);
      if (lookahead == '-') ADVANCE(15);
      if (lookahead == '/') ADVANCE(18);
      if (lookahead == '<') ADVANCE(19);
      if (lookahead == '=') ADVANCE(5);
      if (lookahead == '>') ADVANCE(24);
      if (lookahead == '[') ADVANCE(25);
      if (lookahead == ']') ADVANCE(27);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(8)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_shell_bang);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_BANG);
      if (lookahead == '=') ADVANCE(22);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(36);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(20);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(23);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_unescaped_double_string_fragment);
      if (lookahead == '/') ADVANCE(33);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(34);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_unescaped_double_string_fragment);
      if (lookahead == '/') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(34);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_unescaped_double_string_fragment);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(40);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '/') ADVANCE(39);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(40);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '/') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(40);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(40);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'a') ADVANCE(1);
      if (lookahead == 'f') ADVANCE(2);
      if (lookahead == 'n') ADVANCE(3);
      if (lookahead == 'o') ADVANCE(4);
      if (lookahead == 't') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'n') ADVANCE(6);
      END_STATE();
    case 2:
      if (lookahead == 'a') ADVANCE(7);
      END_STATE();
    case 3:
      if (lookahead == 'i') ADVANCE(8);
      END_STATE();
    case 4:
      if (lookahead == 'r') ADVANCE(9);
      END_STATE();
    case 5:
      if (lookahead == 'r') ADVANCE(10);
      END_STATE();
    case 6:
      if (lookahead == 'd') ADVANCE(11);
      END_STATE();
    case 7:
      if (lookahead == 'l') ADVANCE(12);
      END_STATE();
    case 8:
      if (lookahead == 'l') ADVANCE(13);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_or);
      END_STATE();
    case 10:
      if (lookahead == 'u') ADVANCE(14);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_and);
      END_STATE();
    case 12:
      if (lookahead == 's') ADVANCE(15);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_nil);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 2},
  [48] = {.lex_state = 2},
  [49] = {.lex_state = 2},
  [50] = {.lex_state = 2},
  [51] = {.lex_state = 2},
  [52] = {.lex_state = 2},
  [53] = {.lex_state = 2},
  [54] = {.lex_state = 2},
  [55] = {.lex_state = 2},
  [56] = {.lex_state = 2},
  [57] = {.lex_state = 2},
  [58] = {.lex_state = 2},
  [59] = {.lex_state = 2},
  [60] = {.lex_state = 2},
  [61] = {.lex_state = 2},
  [62] = {.lex_state = 2},
  [63] = {.lex_state = 2},
  [64] = {.lex_state = 2},
  [65] = {.lex_state = 2},
  [66] = {.lex_state = 2},
  [67] = {.lex_state = 2},
  [68] = {.lex_state = 2},
  [69] = {.lex_state = 3},
  [70] = {.lex_state = 3},
  [71] = {.lex_state = 3},
  [72] = {.lex_state = 3},
  [73] = {.lex_state = 3},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 3},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 38},
  [79] = {.lex_state = 0},
  [80] = {(TSStateId)(-1)},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_shell_bang] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
    [anon_sym_or] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_nil] = ACTIONS(1),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(79),
    [sym__expression] = STATE(11),
    [sym_parenthesized_expression] = STATE(3),
    [sym_unary_expression] = STATE(3),
    [sym_binary_expression] = STATE(3),
    [sym_array] = STATE(3),
    [sym__primary] = STATE(3),
    [sym_string] = STATE(7),
    [sym_boolean] = STATE(7),
    [sym_comment] = STATE(1),
    [aux_sym_source_file_repeat1] = STATE(21),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym_shell_bang] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_BANG] = ACTIONS(13),
    [anon_sym_DASH] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [anon_sym_DQUOTE] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [sym_nil] = ACTIONS(7),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [2] = {
    [sym_comment] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(25),
    [sym_identifier] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(25),
    [anon_sym_BANG] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym_and] = ACTIONS(27),
    [anon_sym_or] = ACTIONS(27),
    [anon_sym_PLUS] = ACTIONS(31),
    [anon_sym_STAR] = ACTIONS(33),
    [anon_sym_SLASH] = ACTIONS(35),
    [anon_sym_LT] = ACTIONS(27),
    [anon_sym_LT_EQ] = ACTIONS(25),
    [anon_sym_EQ_EQ] = ACTIONS(25),
    [anon_sym_BANG_EQ] = ACTIONS(25),
    [anon_sym_GT_EQ] = ACTIONS(25),
    [anon_sym_GT] = ACTIONS(27),
    [anon_sym_LBRACK] = ACTIONS(25),
    [sym_number] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(25),
    [anon_sym_true] = ACTIONS(27),
    [anon_sym_false] = ACTIONS(27),
    [sym_nil] = ACTIONS(27),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [3] = {
    [sym_comment] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(37),
    [sym_identifier] = ACTIONS(39),
    [anon_sym_LPAREN] = ACTIONS(37),
    [anon_sym_BANG] = ACTIONS(39),
    [anon_sym_DASH] = ACTIONS(39),
    [anon_sym_and] = ACTIONS(39),
    [anon_sym_or] = ACTIONS(39),
    [anon_sym_PLUS] = ACTIONS(37),
    [anon_sym_STAR] = ACTIONS(37),
    [anon_sym_SLASH] = ACTIONS(39),
    [anon_sym_LT] = ACTIONS(39),
    [anon_sym_LT_EQ] = ACTIONS(37),
    [anon_sym_EQ_EQ] = ACTIONS(37),
    [anon_sym_BANG_EQ] = ACTIONS(37),
    [anon_sym_GT_EQ] = ACTIONS(37),
    [anon_sym_GT] = ACTIONS(39),
    [anon_sym_LBRACK] = ACTIONS(37),
    [sym_number] = ACTIONS(37),
    [anon_sym_DQUOTE] = ACTIONS(37),
    [anon_sym_true] = ACTIONS(39),
    [anon_sym_false] = ACTIONS(39),
    [sym_nil] = ACTIONS(39),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [4] = {
    [sym_comment] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(25),
    [sym_identifier] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(25),
    [anon_sym_BANG] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym_and] = ACTIONS(27),
    [anon_sym_or] = ACTIONS(27),
    [anon_sym_PLUS] = ACTIONS(31),
    [anon_sym_STAR] = ACTIONS(33),
    [anon_sym_SLASH] = ACTIONS(35),
    [anon_sym_LT] = ACTIONS(41),
    [anon_sym_LT_EQ] = ACTIONS(43),
    [anon_sym_EQ_EQ] = ACTIONS(45),
    [anon_sym_BANG_EQ] = ACTIONS(45),
    [anon_sym_GT_EQ] = ACTIONS(43),
    [anon_sym_GT] = ACTIONS(41),
    [anon_sym_LBRACK] = ACTIONS(25),
    [sym_number] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(25),
    [anon_sym_true] = ACTIONS(27),
    [anon_sym_false] = ACTIONS(27),
    [sym_nil] = ACTIONS(27),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [5] = {
    [sym_comment] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(47),
    [sym_identifier] = ACTIONS(49),
    [anon_sym_LPAREN] = ACTIONS(47),
    [anon_sym_BANG] = ACTIONS(49),
    [anon_sym_DASH] = ACTIONS(49),
    [anon_sym_and] = ACTIONS(49),
    [anon_sym_or] = ACTIONS(49),
    [anon_sym_PLUS] = ACTIONS(47),
    [anon_sym_STAR] = ACTIONS(47),
    [anon_sym_SLASH] = ACTIONS(49),
    [anon_sym_LT] = ACTIONS(49),
    [anon_sym_LT_EQ] = ACTIONS(47),
    [anon_sym_EQ_EQ] = ACTIONS(47),
    [anon_sym_BANG_EQ] = ACTIONS(47),
    [anon_sym_GT_EQ] = ACTIONS(47),
    [anon_sym_GT] = ACTIONS(49),
    [anon_sym_LBRACK] = ACTIONS(47),
    [sym_number] = ACTIONS(47),
    [anon_sym_DQUOTE] = ACTIONS(47),
    [anon_sym_true] = ACTIONS(49),
    [anon_sym_false] = ACTIONS(49),
    [sym_nil] = ACTIONS(49),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [6] = {
    [sym_comment] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(25),
    [sym_identifier] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(25),
    [anon_sym_BANG] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_and] = ACTIONS(27),
    [anon_sym_or] = ACTIONS(27),
    [anon_sym_PLUS] = ACTIONS(25),
    [anon_sym_STAR] = ACTIONS(33),
    [anon_sym_SLASH] = ACTIONS(35),
    [anon_sym_LT] = ACTIONS(27),
    [anon_sym_LT_EQ] = ACTIONS(25),
    [anon_sym_EQ_EQ] = ACTIONS(25),
    [anon_sym_BANG_EQ] = ACTIONS(25),
    [anon_sym_GT_EQ] = ACTIONS(25),
    [anon_sym_GT] = ACTIONS(27),
    [anon_sym_LBRACK] = ACTIONS(25),
    [sym_number] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(25),
    [anon_sym_true] = ACTIONS(27),
    [anon_sym_false] = ACTIONS(27),
    [sym_nil] = ACTIONS(27),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [7] = {
    [sym_comment] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(51),
    [sym_identifier] = ACTIONS(53),
    [anon_sym_LPAREN] = ACTIONS(51),
    [anon_sym_BANG] = ACTIONS(53),
    [anon_sym_DASH] = ACTIONS(53),
    [anon_sym_and] = ACTIONS(53),
    [anon_sym_or] = ACTIONS(53),
    [anon_sym_PLUS] = ACTIONS(51),
    [anon_sym_STAR] = ACTIONS(51),
    [anon_sym_SLASH] = ACTIONS(53),
    [anon_sym_LT] = ACTIONS(53),
    [anon_sym_LT_EQ] = ACTIONS(51),
    [anon_sym_EQ_EQ] = ACTIONS(51),
    [anon_sym_BANG_EQ] = ACTIONS(51),
    [anon_sym_GT_EQ] = ACTIONS(51),
    [anon_sym_GT] = ACTIONS(53),
    [anon_sym_LBRACK] = ACTIONS(51),
    [sym_number] = ACTIONS(51),
    [anon_sym_DQUOTE] = ACTIONS(51),
    [anon_sym_true] = ACTIONS(53),
    [anon_sym_false] = ACTIONS(53),
    [sym_nil] = ACTIONS(53),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [8] = {
    [sym_comment] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(55),
    [sym_identifier] = ACTIONS(57),
    [anon_sym_LPAREN] = ACTIONS(55),
    [anon_sym_BANG] = ACTIONS(57),
    [anon_sym_DASH] = ACTIONS(57),
    [anon_sym_and] = ACTIONS(57),
    [anon_sym_or] = ACTIONS(57),
    [anon_sym_PLUS] = ACTIONS(55),
    [anon_sym_STAR] = ACTIONS(55),
    [anon_sym_SLASH] = ACTIONS(57),
    [anon_sym_LT] = ACTIONS(57),
    [anon_sym_LT_EQ] = ACTIONS(55),
    [anon_sym_EQ_EQ] = ACTIONS(55),
    [anon_sym_BANG_EQ] = ACTIONS(55),
    [anon_sym_GT_EQ] = ACTIONS(55),
    [anon_sym_GT] = ACTIONS(57),
    [anon_sym_LBRACK] = ACTIONS(55),
    [sym_number] = ACTIONS(55),
    [anon_sym_DQUOTE] = ACTIONS(55),
    [anon_sym_true] = ACTIONS(57),
    [anon_sym_false] = ACTIONS(57),
    [sym_nil] = ACTIONS(57),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [9] = {
    [sym_comment] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(59),
    [sym_identifier] = ACTIONS(61),
    [anon_sym_LPAREN] = ACTIONS(59),
    [anon_sym_BANG] = ACTIONS(61),
    [anon_sym_DASH] = ACTIONS(61),
    [anon_sym_and] = ACTIONS(61),
    [anon_sym_or] = ACTIONS(61),
    [anon_sym_PLUS] = ACTIONS(59),
    [anon_sym_STAR] = ACTIONS(59),
    [anon_sym_SLASH] = ACTIONS(61),
    [anon_sym_LT] = ACTIONS(61),
    [anon_sym_LT_EQ] = ACTIONS(59),
    [anon_sym_EQ_EQ] = ACTIONS(59),
    [anon_sym_BANG_EQ] = ACTIONS(59),
    [anon_sym_GT_EQ] = ACTIONS(59),
    [anon_sym_GT] = ACTIONS(61),
    [anon_sym_LBRACK] = ACTIONS(59),
    [sym_number] = ACTIONS(59),
    [anon_sym_DQUOTE] = ACTIONS(59),
    [anon_sym_true] = ACTIONS(61),
    [anon_sym_false] = ACTIONS(61),
    [sym_nil] = ACTIONS(61),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [10] = {
    [sym_comment] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(63),
    [sym_identifier] = ACTIONS(65),
    [anon_sym_LPAREN] = ACTIONS(63),
    [anon_sym_BANG] = ACTIONS(65),
    [anon_sym_DASH] = ACTIONS(65),
    [anon_sym_and] = ACTIONS(65),
    [anon_sym_or] = ACTIONS(65),
    [anon_sym_PLUS] = ACTIONS(63),
    [anon_sym_STAR] = ACTIONS(63),
    [anon_sym_SLASH] = ACTIONS(65),
    [anon_sym_LT] = ACTIONS(65),
    [anon_sym_LT_EQ] = ACTIONS(63),
    [anon_sym_EQ_EQ] = ACTIONS(63),
    [anon_sym_BANG_EQ] = ACTIONS(63),
    [anon_sym_GT_EQ] = ACTIONS(63),
    [anon_sym_GT] = ACTIONS(65),
    [anon_sym_LBRACK] = ACTIONS(63),
    [sym_number] = ACTIONS(63),
    [anon_sym_DQUOTE] = ACTIONS(63),
    [anon_sym_true] = ACTIONS(65),
    [anon_sym_false] = ACTIONS(65),
    [sym_nil] = ACTIONS(65),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [11] = {
    [sym_comment] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(67),
    [sym_identifier] = ACTIONS(69),
    [anon_sym_LPAREN] = ACTIONS(67),
    [anon_sym_BANG] = ACTIONS(69),
    [anon_sym_DASH] = ACTIONS(71),
    [anon_sym_and] = ACTIONS(74),
    [anon_sym_or] = ACTIONS(76),
    [anon_sym_PLUS] = ACTIONS(31),
    [anon_sym_STAR] = ACTIONS(33),
    [anon_sym_SLASH] = ACTIONS(35),
    [anon_sym_LT] = ACTIONS(41),
    [anon_sym_LT_EQ] = ACTIONS(43),
    [anon_sym_EQ_EQ] = ACTIONS(45),
    [anon_sym_BANG_EQ] = ACTIONS(45),
    [anon_sym_GT_EQ] = ACTIONS(43),
    [anon_sym_GT] = ACTIONS(41),
    [anon_sym_LBRACK] = ACTIONS(67),
    [sym_number] = ACTIONS(67),
    [anon_sym_DQUOTE] = ACTIONS(67),
    [anon_sym_true] = ACTIONS(69),
    [anon_sym_false] = ACTIONS(69),
    [sym_nil] = ACTIONS(69),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [12] = {
    [sym_comment] = STATE(12),
    [ts_builtin_sym_end] = ACTIONS(25),
    [sym_identifier] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(25),
    [anon_sym_BANG] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_and] = ACTIONS(27),
    [anon_sym_or] = ACTIONS(27),
    [anon_sym_PLUS] = ACTIONS(25),
    [anon_sym_STAR] = ACTIONS(25),
    [anon_sym_SLASH] = ACTIONS(27),
    [anon_sym_LT] = ACTIONS(27),
    [anon_sym_LT_EQ] = ACTIONS(25),
    [anon_sym_EQ_EQ] = ACTIONS(25),
    [anon_sym_BANG_EQ] = ACTIONS(25),
    [anon_sym_GT_EQ] = ACTIONS(25),
    [anon_sym_GT] = ACTIONS(27),
    [anon_sym_LBRACK] = ACTIONS(25),
    [sym_number] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(25),
    [anon_sym_true] = ACTIONS(27),
    [anon_sym_false] = ACTIONS(27),
    [sym_nil] = ACTIONS(27),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [13] = {
    [sym_comment] = STATE(13),
    [ts_builtin_sym_end] = ACTIONS(25),
    [sym_identifier] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(25),
    [anon_sym_BANG] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym_and] = ACTIONS(74),
    [anon_sym_or] = ACTIONS(27),
    [anon_sym_PLUS] = ACTIONS(31),
    [anon_sym_STAR] = ACTIONS(33),
    [anon_sym_SLASH] = ACTIONS(35),
    [anon_sym_LT] = ACTIONS(41),
    [anon_sym_LT_EQ] = ACTIONS(43),
    [anon_sym_EQ_EQ] = ACTIONS(45),
    [anon_sym_BANG_EQ] = ACTIONS(45),
    [anon_sym_GT_EQ] = ACTIONS(43),
    [anon_sym_GT] = ACTIONS(41),
    [anon_sym_LBRACK] = ACTIONS(25),
    [sym_number] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(25),
    [anon_sym_true] = ACTIONS(27),
    [anon_sym_false] = ACTIONS(27),
    [sym_nil] = ACTIONS(27),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [14] = {
    [sym_comment] = STATE(14),
    [ts_builtin_sym_end] = ACTIONS(78),
    [sym_identifier] = ACTIONS(80),
    [anon_sym_LPAREN] = ACTIONS(78),
    [anon_sym_BANG] = ACTIONS(80),
    [anon_sym_DASH] = ACTIONS(80),
    [anon_sym_and] = ACTIONS(80),
    [anon_sym_or] = ACTIONS(80),
    [anon_sym_PLUS] = ACTIONS(78),
    [anon_sym_STAR] = ACTIONS(78),
    [anon_sym_SLASH] = ACTIONS(80),
    [anon_sym_LT] = ACTIONS(80),
    [anon_sym_LT_EQ] = ACTIONS(78),
    [anon_sym_EQ_EQ] = ACTIONS(78),
    [anon_sym_BANG_EQ] = ACTIONS(78),
    [anon_sym_GT_EQ] = ACTIONS(78),
    [anon_sym_GT] = ACTIONS(80),
    [anon_sym_LBRACK] = ACTIONS(78),
    [sym_number] = ACTIONS(78),
    [anon_sym_DQUOTE] = ACTIONS(78),
    [anon_sym_true] = ACTIONS(80),
    [anon_sym_false] = ACTIONS(80),
    [sym_nil] = ACTIONS(80),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [15] = {
    [sym_comment] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(25),
    [sym_identifier] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(25),
    [anon_sym_BANG] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym_and] = ACTIONS(27),
    [anon_sym_or] = ACTIONS(27),
    [anon_sym_PLUS] = ACTIONS(31),
    [anon_sym_STAR] = ACTIONS(33),
    [anon_sym_SLASH] = ACTIONS(35),
    [anon_sym_LT] = ACTIONS(41),
    [anon_sym_LT_EQ] = ACTIONS(43),
    [anon_sym_EQ_EQ] = ACTIONS(25),
    [anon_sym_BANG_EQ] = ACTIONS(25),
    [anon_sym_GT_EQ] = ACTIONS(43),
    [anon_sym_GT] = ACTIONS(41),
    [anon_sym_LBRACK] = ACTIONS(25),
    [sym_number] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(25),
    [anon_sym_true] = ACTIONS(27),
    [anon_sym_false] = ACTIONS(27),
    [sym_nil] = ACTIONS(27),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [16] = {
    [sym_comment] = STATE(16),
    [ts_builtin_sym_end] = ACTIONS(82),
    [sym_identifier] = ACTIONS(84),
    [anon_sym_LPAREN] = ACTIONS(82),
    [anon_sym_BANG] = ACTIONS(84),
    [anon_sym_DASH] = ACTIONS(84),
    [anon_sym_and] = ACTIONS(84),
    [anon_sym_or] = ACTIONS(84),
    [anon_sym_PLUS] = ACTIONS(82),
    [anon_sym_STAR] = ACTIONS(82),
    [anon_sym_SLASH] = ACTIONS(84),
    [anon_sym_LT] = ACTIONS(84),
    [anon_sym_LT_EQ] = ACTIONS(82),
    [anon_sym_EQ_EQ] = ACTIONS(82),
    [anon_sym_BANG_EQ] = ACTIONS(82),
    [anon_sym_GT_EQ] = ACTIONS(82),
    [anon_sym_GT] = ACTIONS(84),
    [anon_sym_LBRACK] = ACTIONS(82),
    [sym_number] = ACTIONS(82),
    [anon_sym_DQUOTE] = ACTIONS(82),
    [anon_sym_true] = ACTIONS(84),
    [anon_sym_false] = ACTIONS(84),
    [sym_nil] = ACTIONS(84),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [17] = {
    [sym_comment] = STATE(17),
    [ts_builtin_sym_end] = ACTIONS(86),
    [sym_identifier] = ACTIONS(88),
    [anon_sym_LPAREN] = ACTIONS(86),
    [anon_sym_BANG] = ACTIONS(88),
    [anon_sym_DASH] = ACTIONS(88),
    [anon_sym_and] = ACTIONS(88),
    [anon_sym_or] = ACTIONS(88),
    [anon_sym_PLUS] = ACTIONS(86),
    [anon_sym_STAR] = ACTIONS(86),
    [anon_sym_SLASH] = ACTIONS(88),
    [anon_sym_LT] = ACTIONS(88),
    [anon_sym_LT_EQ] = ACTIONS(86),
    [anon_sym_EQ_EQ] = ACTIONS(86),
    [anon_sym_BANG_EQ] = ACTIONS(86),
    [anon_sym_GT_EQ] = ACTIONS(86),
    [anon_sym_GT] = ACTIONS(88),
    [anon_sym_LBRACK] = ACTIONS(86),
    [sym_number] = ACTIONS(86),
    [anon_sym_DQUOTE] = ACTIONS(86),
    [anon_sym_true] = ACTIONS(88),
    [anon_sym_false] = ACTIONS(88),
    [sym_nil] = ACTIONS(88),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [18] = {
    [sym_comment] = STATE(18),
    [ts_builtin_sym_end] = ACTIONS(90),
    [sym_identifier] = ACTIONS(92),
    [anon_sym_LPAREN] = ACTIONS(90),
    [anon_sym_BANG] = ACTIONS(92),
    [anon_sym_DASH] = ACTIONS(92),
    [anon_sym_and] = ACTIONS(92),
    [anon_sym_or] = ACTIONS(92),
    [anon_sym_PLUS] = ACTIONS(90),
    [anon_sym_STAR] = ACTIONS(90),
    [anon_sym_SLASH] = ACTIONS(92),
    [anon_sym_LT] = ACTIONS(92),
    [anon_sym_LT_EQ] = ACTIONS(90),
    [anon_sym_EQ_EQ] = ACTIONS(90),
    [anon_sym_BANG_EQ] = ACTIONS(90),
    [anon_sym_GT_EQ] = ACTIONS(90),
    [anon_sym_GT] = ACTIONS(92),
    [anon_sym_LBRACK] = ACTIONS(90),
    [sym_number] = ACTIONS(90),
    [anon_sym_DQUOTE] = ACTIONS(90),
    [anon_sym_true] = ACTIONS(92),
    [anon_sym_false] = ACTIONS(92),
    [sym_nil] = ACTIONS(92),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [19] = {
    [sym_comment] = STATE(19),
    [ts_builtin_sym_end] = ACTIONS(94),
    [sym_identifier] = ACTIONS(96),
    [anon_sym_LPAREN] = ACTIONS(94),
    [anon_sym_BANG] = ACTIONS(96),
    [anon_sym_DASH] = ACTIONS(96),
    [anon_sym_and] = ACTIONS(96),
    [anon_sym_or] = ACTIONS(96),
    [anon_sym_PLUS] = ACTIONS(94),
    [anon_sym_STAR] = ACTIONS(94),
    [anon_sym_SLASH] = ACTIONS(96),
    [anon_sym_LT] = ACTIONS(96),
    [anon_sym_LT_EQ] = ACTIONS(94),
    [anon_sym_EQ_EQ] = ACTIONS(94),
    [anon_sym_BANG_EQ] = ACTIONS(94),
    [anon_sym_GT_EQ] = ACTIONS(94),
    [anon_sym_GT] = ACTIONS(96),
    [anon_sym_LBRACK] = ACTIONS(94),
    [sym_number] = ACTIONS(94),
    [anon_sym_DQUOTE] = ACTIONS(94),
    [anon_sym_true] = ACTIONS(96),
    [anon_sym_false] = ACTIONS(96),
    [sym_nil] = ACTIONS(96),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [20] = {
    [sym__expression] = STATE(11),
    [sym_parenthesized_expression] = STATE(3),
    [sym_unary_expression] = STATE(3),
    [sym_binary_expression] = STATE(3),
    [sym_array] = STATE(3),
    [sym__primary] = STATE(3),
    [sym_string] = STATE(7),
    [sym_boolean] = STATE(7),
    [sym_comment] = STATE(20),
    [aux_sym_source_file_repeat1] = STATE(22),
    [ts_builtin_sym_end] = ACTIONS(98),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_BANG] = ACTIONS(13),
    [anon_sym_DASH] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [anon_sym_DQUOTE] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [sym_nil] = ACTIONS(7),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [21] = {
    [sym__expression] = STATE(11),
    [sym_parenthesized_expression] = STATE(3),
    [sym_unary_expression] = STATE(3),
    [sym_binary_expression] = STATE(3),
    [sym_array] = STATE(3),
    [sym__primary] = STATE(3),
    [sym_string] = STATE(7),
    [sym_boolean] = STATE(7),
    [sym_comment] = STATE(21),
    [aux_sym_source_file_repeat1] = STATE(23),
    [ts_builtin_sym_end] = ACTIONS(98),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_BANG] = ACTIONS(13),
    [anon_sym_DASH] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [anon_sym_DQUOTE] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [sym_nil] = ACTIONS(7),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [22] = {
    [sym__expression] = STATE(11),
    [sym_parenthesized_expression] = STATE(3),
    [sym_unary_expression] = STATE(3),
    [sym_binary_expression] = STATE(3),
    [sym_array] = STATE(3),
    [sym__primary] = STATE(3),
    [sym_string] = STATE(7),
    [sym_boolean] = STATE(7),
    [sym_comment] = STATE(22),
    [aux_sym_source_file_repeat1] = STATE(23),
    [ts_builtin_sym_end] = ACTIONS(100),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_BANG] = ACTIONS(13),
    [anon_sym_DASH] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [anon_sym_DQUOTE] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [sym_nil] = ACTIONS(7),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [23] = {
    [sym__expression] = STATE(11),
    [sym_parenthesized_expression] = STATE(3),
    [sym_unary_expression] = STATE(3),
    [sym_binary_expression] = STATE(3),
    [sym_array] = STATE(3),
    [sym__primary] = STATE(3),
    [sym_string] = STATE(7),
    [sym_boolean] = STATE(7),
    [sym_comment] = STATE(23),
    [aux_sym_source_file_repeat1] = STATE(23),
    [ts_builtin_sym_end] = ACTIONS(102),
    [sym_identifier] = ACTIONS(104),
    [anon_sym_LPAREN] = ACTIONS(107),
    [anon_sym_BANG] = ACTIONS(110),
    [anon_sym_DASH] = ACTIONS(113),
    [anon_sym_LBRACK] = ACTIONS(116),
    [sym_number] = ACTIONS(119),
    [anon_sym_DQUOTE] = ACTIONS(122),
    [anon_sym_true] = ACTIONS(125),
    [anon_sym_false] = ACTIONS(125),
    [sym_nil] = ACTIONS(104),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(130), 1,
      anon_sym_LPAREN,
    ACTIONS(132), 1,
      anon_sym_BANG,
    ACTIONS(134), 1,
      anon_sym_DASH,
    ACTIONS(136), 1,
      anon_sym_LBRACK,
    ACTIONS(138), 1,
      anon_sym_RBRACK,
    ACTIONS(140), 1,
      sym_number,
    ACTIONS(142), 1,
      anon_sym_DQUOTE,
    STATE(24), 1,
      sym_comment,
    STATE(66), 1,
      sym__expression,
    ACTIONS(128), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(144), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(55), 2,
      sym_string,
      sym_boolean,
    STATE(50), 5,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [50] = 14,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(130), 1,
      anon_sym_LPAREN,
    ACTIONS(132), 1,
      anon_sym_BANG,
    ACTIONS(134), 1,
      anon_sym_DASH,
    ACTIONS(136), 1,
      anon_sym_LBRACK,
    ACTIONS(140), 1,
      sym_number,
    ACTIONS(142), 1,
      anon_sym_DQUOTE,
    ACTIONS(146), 1,
      anon_sym_RBRACK,
    STATE(25), 1,
      sym_comment,
    STATE(66), 1,
      sym__expression,
    ACTIONS(128), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(144), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(55), 2,
      sym_string,
      sym_boolean,
    STATE(50), 5,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [100] = 14,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(130), 1,
      anon_sym_LPAREN,
    ACTIONS(132), 1,
      anon_sym_BANG,
    ACTIONS(134), 1,
      anon_sym_DASH,
    ACTIONS(136), 1,
      anon_sym_LBRACK,
    ACTIONS(140), 1,
      sym_number,
    ACTIONS(142), 1,
      anon_sym_DQUOTE,
    ACTIONS(148), 1,
      anon_sym_RBRACK,
    STATE(26), 1,
      sym_comment,
    STATE(66), 1,
      sym__expression,
    ACTIONS(128), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(144), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(55), 2,
      sym_string,
      sym_boolean,
    STATE(50), 5,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [150] = 14,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(130), 1,
      anon_sym_LPAREN,
    ACTIONS(132), 1,
      anon_sym_BANG,
    ACTIONS(134), 1,
      anon_sym_DASH,
    ACTIONS(136), 1,
      anon_sym_LBRACK,
    ACTIONS(140), 1,
      sym_number,
    ACTIONS(142), 1,
      anon_sym_DQUOTE,
    ACTIONS(150), 1,
      anon_sym_RBRACK,
    STATE(27), 1,
      sym_comment,
    STATE(54), 1,
      sym__expression,
    ACTIONS(128), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(144), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(55), 2,
      sym_string,
      sym_boolean,
    STATE(50), 5,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [200] = 14,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(130), 1,
      anon_sym_LPAREN,
    ACTIONS(132), 1,
      anon_sym_BANG,
    ACTIONS(134), 1,
      anon_sym_DASH,
    ACTIONS(136), 1,
      anon_sym_LBRACK,
    ACTIONS(140), 1,
      sym_number,
    ACTIONS(142), 1,
      anon_sym_DQUOTE,
    ACTIONS(152), 1,
      anon_sym_RBRACK,
    STATE(28), 1,
      sym_comment,
    STATE(47), 1,
      sym__expression,
    ACTIONS(128), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(144), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(55), 2,
      sym_string,
      sym_boolean,
    STATE(50), 5,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [250] = 14,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(130), 1,
      anon_sym_LPAREN,
    ACTIONS(132), 1,
      anon_sym_BANG,
    ACTIONS(134), 1,
      anon_sym_DASH,
    ACTIONS(136), 1,
      anon_sym_LBRACK,
    ACTIONS(140), 1,
      sym_number,
    ACTIONS(142), 1,
      anon_sym_DQUOTE,
    ACTIONS(154), 1,
      anon_sym_RBRACK,
    STATE(29), 1,
      sym_comment,
    STATE(66), 1,
      sym__expression,
    ACTIONS(128), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(144), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(55), 2,
      sym_string,
      sym_boolean,
    STATE(50), 5,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [300] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(130), 1,
      anon_sym_LPAREN,
    ACTIONS(132), 1,
      anon_sym_BANG,
    ACTIONS(134), 1,
      anon_sym_DASH,
    ACTIONS(136), 1,
      anon_sym_LBRACK,
    ACTIONS(140), 1,
      sym_number,
    ACTIONS(142), 1,
      anon_sym_DQUOTE,
    STATE(30), 1,
      sym_comment,
    STATE(48), 1,
      sym__expression,
    ACTIONS(128), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(144), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(55), 2,
      sym_string,
      sym_boolean,
    STATE(50), 5,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [347] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_BANG,
    ACTIONS(15), 1,
      anon_sym_DASH,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      sym_number,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    STATE(13), 1,
      sym__expression,
    STATE(31), 1,
      sym_comment,
    ACTIONS(7), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(7), 2,
      sym_string,
      sym_boolean,
    STATE(3), 5,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [394] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_BANG,
    ACTIONS(15), 1,
      anon_sym_DASH,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      sym_number,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    STATE(12), 1,
      sym__expression,
    STATE(32), 1,
      sym_comment,
    ACTIONS(7), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(7), 2,
      sym_string,
      sym_boolean,
    STATE(3), 5,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [441] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(130), 1,
      anon_sym_LPAREN,
    ACTIONS(132), 1,
      anon_sym_BANG,
    ACTIONS(134), 1,
      anon_sym_DASH,
    ACTIONS(136), 1,
      anon_sym_LBRACK,
    ACTIONS(140), 1,
      sym_number,
    ACTIONS(142), 1,
      anon_sym_DQUOTE,
    STATE(33), 1,
      sym_comment,
    STATE(65), 1,
      sym__expression,
    ACTIONS(128), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(144), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(55), 2,
      sym_string,
      sym_boolean,
    STATE(50), 5,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [488] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_BANG,
    ACTIONS(15), 1,
      anon_sym_DASH,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      sym_number,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    STATE(2), 1,
      sym__expression,
    STATE(34), 1,
      sym_comment,
    ACTIONS(7), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(7), 2,
      sym_string,
      sym_boolean,
    STATE(3), 5,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [535] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(130), 1,
      anon_sym_LPAREN,
    ACTIONS(132), 1,
      anon_sym_BANG,
    ACTIONS(134), 1,
      anon_sym_DASH,
    ACTIONS(136), 1,
      anon_sym_LBRACK,
    ACTIONS(140), 1,
      sym_number,
    ACTIONS(142), 1,
      anon_sym_DQUOTE,
    STATE(35), 1,
      sym_comment,
    STATE(64), 1,
      sym__expression,
    ACTIONS(128), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(144), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(55), 2,
      sym_string,
      sym_boolean,
    STATE(50), 5,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [582] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_BANG,
    ACTIONS(15), 1,
      anon_sym_DASH,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      sym_number,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    STATE(15), 1,
      sym__expression,
    STATE(36), 1,
      sym_comment,
    ACTIONS(7), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(7), 2,
      sym_string,
      sym_boolean,
    STATE(3), 5,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [629] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_BANG,
    ACTIONS(15), 1,
      anon_sym_DASH,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      sym_number,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    STATE(6), 1,
      sym__expression,
    STATE(37), 1,
      sym_comment,
    ACTIONS(7), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(7), 2,
      sym_string,
      sym_boolean,
    STATE(3), 5,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [676] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_BANG,
    ACTIONS(15), 1,
      anon_sym_DASH,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      sym_number,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    STATE(4), 1,
      sym__expression,
    STATE(38), 1,
      sym_comment,
    ACTIONS(7), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(7), 2,
      sym_string,
      sym_boolean,
    STATE(3), 5,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [723] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(130), 1,
      anon_sym_LPAREN,
    ACTIONS(132), 1,
      anon_sym_BANG,
    ACTIONS(134), 1,
      anon_sym_DASH,
    ACTIONS(136), 1,
      anon_sym_LBRACK,
    ACTIONS(140), 1,
      sym_number,
    ACTIONS(142), 1,
      anon_sym_DQUOTE,
    STATE(39), 1,
      sym_comment,
    STATE(68), 1,
      sym__expression,
    ACTIONS(128), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(144), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(55), 2,
      sym_string,
      sym_boolean,
    STATE(50), 5,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [770] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(130), 1,
      anon_sym_LPAREN,
    ACTIONS(132), 1,
      anon_sym_BANG,
    ACTIONS(134), 1,
      anon_sym_DASH,
    ACTIONS(136), 1,
      anon_sym_LBRACK,
    ACTIONS(140), 1,
      sym_number,
    ACTIONS(142), 1,
      anon_sym_DQUOTE,
    STATE(40), 1,
      sym_comment,
    STATE(63), 1,
      sym__expression,
    ACTIONS(128), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(144), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(55), 2,
      sym_string,
      sym_boolean,
    STATE(50), 5,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [817] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(130), 1,
      anon_sym_LPAREN,
    ACTIONS(132), 1,
      anon_sym_BANG,
    ACTIONS(134), 1,
      anon_sym_DASH,
    ACTIONS(136), 1,
      anon_sym_LBRACK,
    ACTIONS(140), 1,
      sym_number,
    ACTIONS(142), 1,
      anon_sym_DQUOTE,
    STATE(41), 1,
      sym_comment,
    STATE(58), 1,
      sym__expression,
    ACTIONS(128), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(144), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(55), 2,
      sym_string,
      sym_boolean,
    STATE(50), 5,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [864] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(130), 1,
      anon_sym_LPAREN,
    ACTIONS(132), 1,
      anon_sym_BANG,
    ACTIONS(134), 1,
      anon_sym_DASH,
    ACTIONS(136), 1,
      anon_sym_LBRACK,
    ACTIONS(140), 1,
      sym_number,
    ACTIONS(142), 1,
      anon_sym_DQUOTE,
    STATE(42), 1,
      sym_comment,
    STATE(51), 1,
      sym__expression,
    ACTIONS(128), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(144), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(55), 2,
      sym_string,
      sym_boolean,
    STATE(50), 5,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [911] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_BANG,
    ACTIONS(15), 1,
      anon_sym_DASH,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      sym_number,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    STATE(17), 1,
      sym__expression,
    STATE(43), 1,
      sym_comment,
    ACTIONS(7), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(7), 2,
      sym_string,
      sym_boolean,
    STATE(3), 5,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [958] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(130), 1,
      anon_sym_LPAREN,
    ACTIONS(132), 1,
      anon_sym_BANG,
    ACTIONS(134), 1,
      anon_sym_DASH,
    ACTIONS(136), 1,
      anon_sym_LBRACK,
    ACTIONS(140), 1,
      sym_number,
    ACTIONS(142), 1,
      anon_sym_DQUOTE,
    STATE(44), 1,
      sym_comment,
    STATE(67), 1,
      sym__expression,
    ACTIONS(128), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(144), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(55), 2,
      sym_string,
      sym_boolean,
    STATE(50), 5,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [1005] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(130), 1,
      anon_sym_LPAREN,
    ACTIONS(132), 1,
      anon_sym_BANG,
    ACTIONS(134), 1,
      anon_sym_DASH,
    ACTIONS(136), 1,
      anon_sym_LBRACK,
    ACTIONS(140), 1,
      sym_number,
    ACTIONS(142), 1,
      anon_sym_DQUOTE,
    STATE(45), 1,
      sym_comment,
    STATE(66), 1,
      sym__expression,
    ACTIONS(128), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(144), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(55), 2,
      sym_string,
      sym_boolean,
    STATE(50), 5,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [1052] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(130), 1,
      anon_sym_LPAREN,
    ACTIONS(132), 1,
      anon_sym_BANG,
    ACTIONS(134), 1,
      anon_sym_DASH,
    ACTIONS(136), 1,
      anon_sym_LBRACK,
    ACTIONS(140), 1,
      sym_number,
    ACTIONS(142), 1,
      anon_sym_DQUOTE,
    STATE(46), 1,
      sym_comment,
    STATE(62), 1,
      sym__expression,
    ACTIONS(128), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(144), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(55), 2,
      sym_string,
      sym_boolean,
    STATE(50), 5,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [1099] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(158), 1,
      anon_sym_and,
    ACTIONS(160), 1,
      anon_sym_or,
    ACTIONS(162), 1,
      anon_sym_STAR,
    ACTIONS(164), 1,
      anon_sym_SLASH,
    ACTIONS(172), 1,
      anon_sym_COMMA,
    ACTIONS(174), 1,
      anon_sym_RBRACK,
    STATE(47), 1,
      sym_comment,
    STATE(75), 1,
      aux_sym_array_repeat1,
    ACTIONS(156), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(166), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(168), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(170), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1143] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(162), 1,
      anon_sym_STAR,
    ACTIONS(164), 1,
      anon_sym_SLASH,
    STATE(48), 1,
      sym_comment,
    ACTIONS(27), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(156), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(25), 9,
      anon_sym_RPAREN,
      anon_sym_and,
      anon_sym_or,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1175] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(49), 1,
      sym_comment,
    ACTIONS(61), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(59), 12,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1201] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(50), 1,
      sym_comment,
    ACTIONS(39), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(37), 12,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1227] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(51), 1,
      sym_comment,
    ACTIONS(88), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(86), 12,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1253] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(52), 1,
      sym_comment,
    ACTIONS(92), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(90), 12,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1279] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(53), 1,
      sym_comment,
    ACTIONS(84), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(82), 12,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1305] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(158), 1,
      anon_sym_and,
    ACTIONS(160), 1,
      anon_sym_or,
    ACTIONS(162), 1,
      anon_sym_STAR,
    ACTIONS(164), 1,
      anon_sym_SLASH,
    ACTIONS(176), 1,
      anon_sym_COMMA,
    ACTIONS(178), 1,
      anon_sym_RBRACK,
    STATE(54), 1,
      sym_comment,
    STATE(77), 1,
      aux_sym_array_repeat1,
    ACTIONS(156), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(166), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(168), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(170), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1349] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(55), 1,
      sym_comment,
    ACTIONS(53), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(51), 12,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1375] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(56), 1,
      sym_comment,
    ACTIONS(96), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(94), 12,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1401] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(57), 1,
      sym_comment,
    ACTIONS(49), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(47), 12,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1427] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(162), 1,
      anon_sym_STAR,
    ACTIONS(164), 1,
      anon_sym_SLASH,
    STATE(58), 1,
      sym_comment,
    ACTIONS(156), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(166), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(168), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(25), 7,
      anon_sym_RPAREN,
      anon_sym_and,
      anon_sym_or,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1461] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(59), 1,
      sym_comment,
    ACTIONS(65), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(63), 12,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1487] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(60), 1,
      sym_comment,
    ACTIONS(57), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(55), 12,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1513] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(61), 1,
      sym_comment,
    ACTIONS(80), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(78), 12,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1539] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(162), 1,
      anon_sym_STAR,
    ACTIONS(164), 1,
      anon_sym_SLASH,
    STATE(62), 1,
      sym_comment,
    ACTIONS(27), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(25), 11,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1569] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(162), 1,
      anon_sym_STAR,
    ACTIONS(164), 1,
      anon_sym_SLASH,
    STATE(63), 1,
      sym_comment,
    ACTIONS(156), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(166), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(168), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(170), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(25), 5,
      anon_sym_RPAREN,
      anon_sym_and,
      anon_sym_or,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1605] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(158), 1,
      anon_sym_and,
    ACTIONS(162), 1,
      anon_sym_STAR,
    ACTIONS(164), 1,
      anon_sym_SLASH,
    STATE(64), 1,
      sym_comment,
    ACTIONS(156), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(166), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(168), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(170), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(25), 4,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1643] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(65), 1,
      sym_comment,
    ACTIONS(27), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(25), 12,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1669] = 11,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(158), 1,
      anon_sym_and,
    ACTIONS(160), 1,
      anon_sym_or,
    ACTIONS(162), 1,
      anon_sym_STAR,
    ACTIONS(164), 1,
      anon_sym_SLASH,
    STATE(66), 1,
      sym_comment,
    ACTIONS(156), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(166), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(168), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(170), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(180), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1708] = 11,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(158), 1,
      anon_sym_and,
    ACTIONS(160), 1,
      anon_sym_or,
    ACTIONS(162), 1,
      anon_sym_STAR,
    ACTIONS(164), 1,
      anon_sym_SLASH,
    ACTIONS(182), 1,
      anon_sym_RPAREN,
    STATE(67), 1,
      sym_comment,
    ACTIONS(156), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(166), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(168), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(170), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1746] = 11,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(158), 1,
      anon_sym_and,
    ACTIONS(160), 1,
      anon_sym_or,
    ACTIONS(162), 1,
      anon_sym_STAR,
    ACTIONS(164), 1,
      anon_sym_SLASH,
    ACTIONS(184), 1,
      anon_sym_RPAREN,
    STATE(68), 1,
      sym_comment,
    ACTIONS(156), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(166), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(168), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(170), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1784] = 5,
    ACTIONS(186), 1,
      anon_sym_DQUOTE,
    ACTIONS(190), 1,
      anon_sym_SLASH_SLASH,
    STATE(69), 1,
      sym_comment,
    STATE(70), 1,
      aux_sym_string_repeat1,
    ACTIONS(188), 2,
      sym_unescaped_double_string_fragment,
      sym_escape_sequence,
  [1801] = 4,
    ACTIONS(190), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(192), 1,
      anon_sym_DQUOTE,
    ACTIONS(194), 2,
      sym_unescaped_double_string_fragment,
      sym_escape_sequence,
    STATE(70), 2,
      sym_comment,
      aux_sym_string_repeat1,
  [1816] = 5,
    ACTIONS(190), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(197), 1,
      anon_sym_DQUOTE,
    STATE(71), 1,
      sym_comment,
    STATE(72), 1,
      aux_sym_string_repeat1,
    ACTIONS(188), 2,
      sym_unescaped_double_string_fragment,
      sym_escape_sequence,
  [1833] = 5,
    ACTIONS(190), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(199), 1,
      anon_sym_DQUOTE,
    STATE(70), 1,
      aux_sym_string_repeat1,
    STATE(72), 1,
      sym_comment,
    ACTIONS(188), 2,
      sym_unescaped_double_string_fragment,
      sym_escape_sequence,
  [1850] = 5,
    ACTIONS(190), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(201), 1,
      anon_sym_DQUOTE,
    STATE(69), 1,
      aux_sym_string_repeat1,
    STATE(73), 1,
      sym_comment,
    ACTIONS(188), 2,
      sym_unescaped_double_string_fragment,
      sym_escape_sequence,
  [1867] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(180), 1,
      anon_sym_RBRACK,
    ACTIONS(203), 1,
      anon_sym_COMMA,
    STATE(74), 2,
      sym_comment,
      aux_sym_array_repeat1,
  [1881] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(146), 1,
      anon_sym_RBRACK,
    ACTIONS(206), 1,
      anon_sym_COMMA,
    STATE(74), 1,
      aux_sym_array_repeat1,
    STATE(75), 1,
      sym_comment,
  [1897] = 4,
    ACTIONS(190), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(208), 1,
      anon_sym_DQUOTE,
    STATE(76), 1,
      sym_comment,
    ACTIONS(210), 2,
      sym_unescaped_double_string_fragment,
      sym_escape_sequence,
  [1911] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(138), 1,
      anon_sym_RBRACK,
    ACTIONS(212), 1,
      anon_sym_COMMA,
    STATE(74), 1,
      aux_sym_array_repeat1,
    STATE(77), 1,
      sym_comment,
  [1927] = 3,
    ACTIONS(190), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(214), 1,
      aux_sym_comment_token1,
    STATE(78), 1,
      sym_comment,
  [1937] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(216), 1,
      ts_builtin_sym_end,
    STATE(79), 1,
      sym_comment,
  [1947] = 1,
    ACTIONS(218), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(24)] = 0,
  [SMALL_STATE(25)] = 50,
  [SMALL_STATE(26)] = 100,
  [SMALL_STATE(27)] = 150,
  [SMALL_STATE(28)] = 200,
  [SMALL_STATE(29)] = 250,
  [SMALL_STATE(30)] = 300,
  [SMALL_STATE(31)] = 347,
  [SMALL_STATE(32)] = 394,
  [SMALL_STATE(33)] = 441,
  [SMALL_STATE(34)] = 488,
  [SMALL_STATE(35)] = 535,
  [SMALL_STATE(36)] = 582,
  [SMALL_STATE(37)] = 629,
  [SMALL_STATE(38)] = 676,
  [SMALL_STATE(39)] = 723,
  [SMALL_STATE(40)] = 770,
  [SMALL_STATE(41)] = 817,
  [SMALL_STATE(42)] = 864,
  [SMALL_STATE(43)] = 911,
  [SMALL_STATE(44)] = 958,
  [SMALL_STATE(45)] = 1005,
  [SMALL_STATE(46)] = 1052,
  [SMALL_STATE(47)] = 1099,
  [SMALL_STATE(48)] = 1143,
  [SMALL_STATE(49)] = 1175,
  [SMALL_STATE(50)] = 1201,
  [SMALL_STATE(51)] = 1227,
  [SMALL_STATE(52)] = 1253,
  [SMALL_STATE(53)] = 1279,
  [SMALL_STATE(54)] = 1305,
  [SMALL_STATE(55)] = 1349,
  [SMALL_STATE(56)] = 1375,
  [SMALL_STATE(57)] = 1401,
  [SMALL_STATE(58)] = 1427,
  [SMALL_STATE(59)] = 1461,
  [SMALL_STATE(60)] = 1487,
  [SMALL_STATE(61)] = 1513,
  [SMALL_STATE(62)] = 1539,
  [SMALL_STATE(63)] = 1569,
  [SMALL_STATE(64)] = 1605,
  [SMALL_STATE(65)] = 1643,
  [SMALL_STATE(66)] = 1669,
  [SMALL_STATE(67)] = 1708,
  [SMALL_STATE(68)] = 1746,
  [SMALL_STATE(69)] = 1784,
  [SMALL_STATE(70)] = 1801,
  [SMALL_STATE(71)] = 1816,
  [SMALL_STATE(72)] = 1833,
  [SMALL_STATE(73)] = 1850,
  [SMALL_STATE(74)] = 1867,
  [SMALL_STATE(75)] = 1881,
  [SMALL_STATE(76)] = 1897,
  [SMALL_STATE(77)] = 1911,
  [SMALL_STATE(78)] = 1927,
  [SMALL_STATE(79)] = 1937,
  [SMALL_STATE(80)] = 1947,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, .production_id = 2),
  [27] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, .production_id = 2),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 4),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 4),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__primary, 1),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__primary, 1),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 3),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized_expression, 3),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parenthesized_expression, 3),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1),
  [71] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1), SHIFT(37),
  [74] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [76] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expression, 2, .production_id = 1),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_expression, 2, .production_id = 1),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 2),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 5),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 5),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [104] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(7),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(44),
  [110] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(43),
  [113] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(43),
  [116] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(28),
  [119] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(7),
  [122] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(73),
  [125] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(9),
  [128] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [134] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [144] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [164] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [166] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [186] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [190] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2),
  [194] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(76),
  [197] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [199] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [201] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [203] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(45),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [208] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 1),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 1),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [214] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [216] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_lx(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
