#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 99
#define LARGE_STATE_COUNT 28
#define SYMBOL_COUNT 44
#define ALIAS_COUNT 0
#define TOKEN_COUNT 30
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 3

enum {
  sym_identifier = 1,
  sym_shell_bang = 2,
  anon_sym_LPAREN = 3,
  anon_sym_RPAREN = 4,
  anon_sym_COMMA = 5,
  anon_sym_BANG = 6,
  anon_sym_DASH = 7,
  anon_sym_and = 8,
  anon_sym_or = 9,
  anon_sym_PLUS = 10,
  anon_sym_STAR = 11,
  anon_sym_SLASH = 12,
  anon_sym_LT = 13,
  anon_sym_LT_EQ = 14,
  anon_sym_EQ_EQ = 15,
  anon_sym_BANG_EQ = 16,
  anon_sym_GT_EQ = 17,
  anon_sym_GT = 18,
  anon_sym_LBRACK = 19,
  anon_sym_RBRACK = 20,
  sym_number = 21,
  anon_sym_DQUOTE = 22,
  sym_unescaped_double_string_fragment = 23,
  sym_escape_sequence = 24,
  anon_sym_true = 25,
  anon_sym_false = 26,
  sym_nil = 27,
  anon_sym_SLASH_SLASH = 28,
  aux_sym_comment_token1 = 29,
  sym_source_file = 30,
  sym__expression = 31,
  sym_parenthesized_expression = 32,
  sym_call = 33,
  sym_unary_expression = 34,
  sym_binary_expression = 35,
  sym_array = 36,
  sym__primary = 37,
  sym_string = 38,
  sym_boolean = 39,
  sym_comment = 40,
  aux_sym_source_file_repeat1 = 41,
  aux_sym_call_repeat1 = 42,
  aux_sym_string_repeat1 = 43,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_shell_bang] = "shell_bang",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COMMA] = ",",
  [anon_sym_BANG] = "!",
  [anon_sym_DASH] = "-",
  [anon_sym_and] = "and",
  [anon_sym_or] = "or",
  [anon_sym_PLUS] = "+",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_LT] = "<",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_GT] = ">",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_number] = "number",
  [anon_sym_DQUOTE] = "\"",
  [sym_unescaped_double_string_fragment] = "string_fragment",
  [sym_escape_sequence] = "escape_sequence",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_nil] = "nil",
  [anon_sym_SLASH_SLASH] = "//",
  [aux_sym_comment_token1] = "comment_token1",
  [sym_source_file] = "source_file",
  [sym__expression] = "_expression",
  [sym_parenthesized_expression] = "parenthesized_expression",
  [sym_call] = "call",
  [sym_unary_expression] = "unary_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_array] = "array",
  [sym__primary] = "_primary",
  [sym_string] = "string",
  [sym_boolean] = "boolean",
  [sym_comment] = "comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_call_repeat1] = "call_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_shell_bang] = sym_shell_bang,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_and] = anon_sym_and,
  [anon_sym_or] = anon_sym_or,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_number] = sym_number,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym_unescaped_double_string_fragment] = sym_unescaped_double_string_fragment,
  [sym_escape_sequence] = sym_escape_sequence,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_nil] = sym_nil,
  [anon_sym_SLASH_SLASH] = anon_sym_SLASH_SLASH,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [sym_source_file] = sym_source_file,
  [sym__expression] = sym__expression,
  [sym_parenthesized_expression] = sym_parenthesized_expression,
  [sym_call] = sym_call,
  [sym_unary_expression] = sym_unary_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_array] = sym_array,
  [sym__primary] = sym__primary,
  [sym_string] = sym_string,
  [sym_boolean] = sym_boolean,
  [sym_comment] = sym_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_call_repeat1] = aux_sym_call_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_shell_bang] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_or] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_unescaped_double_string_fragment] = {
    .visible = true,
    .named = true,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_nil] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_parenthesized_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym__primary] = {
    .visible = false,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_call_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_left = 1,
  field_operator = 2,
  field_right = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_left] = "left",
  [field_operator] = "operator",
  [field_right] = "right",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_operator, 0},
    {field_right, 1},
  [2] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 30,
  [32] = 32,
  [33] = 33,
  [34] = 29,
  [35] = 33,
  [36] = 32,
  [37] = 37,
  [38] = 28,
  [39] = 37,
  [40] = 40,
  [41] = 40,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 45,
  [47] = 47,
  [48] = 47,
  [49] = 49,
  [50] = 50,
  [51] = 49,
  [52] = 50,
  [53] = 53,
  [54] = 42,
  [55] = 43,
  [56] = 44,
  [57] = 21,
  [58] = 22,
  [59] = 59,
  [60] = 60,
  [61] = 59,
  [62] = 62,
  [63] = 3,
  [64] = 9,
  [65] = 2,
  [66] = 17,
  [67] = 18,
  [68] = 20,
  [69] = 10,
  [70] = 8,
  [71] = 5,
  [72] = 13,
  [73] = 23,
  [74] = 7,
  [75] = 4,
  [76] = 19,
  [77] = 15,
  [78] = 62,
  [79] = 6,
  [80] = 12,
  [81] = 14,
  [82] = 16,
  [83] = 83,
  [84] = 83,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 86,
  [89] = 87,
  [90] = 90,
  [91] = 91,
  [92] = 91,
  [93] = 93,
  [94] = 94,
  [95] = 94,
  [96] = 96,
  [97] = 97,
  [98] = 98,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(9);
      if (lookahead == '!') ADVANCE(14);
      if (lookahead == '"') ADVANCE(31);
      if (lookahead == '#') ADVANCE(1);
      if (lookahead == '(') ADVANCE(11);
      if (lookahead == ')') ADVANCE(12);
      if (lookahead == '*') ADVANCE(18);
      if (lookahead == '+') ADVANCE(17);
      if (lookahead == ',') ADVANCE(13);
      if (lookahead == '-') ADVANCE(16);
      if (lookahead == '/') ADVANCE(19);
      if (lookahead == '<') ADVANCE(20);
      if (lookahead == '=') ADVANCE(5);
      if (lookahead == '>') ADVANCE(25);
      if (lookahead == '[') ADVANCE(26);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead == ']') ADVANCE(27);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(8)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(10);
      END_STATE();
    case 2:
      if (lookahead == '!') ADVANCE(4);
      if (lookahead == '(') ADVANCE(11);
      if (lookahead == ')') ADVANCE(12);
      if (lookahead == '*') ADVANCE(18);
      if (lookahead == '+') ADVANCE(17);
      if (lookahead == ',') ADVANCE(13);
      if (lookahead == '-') ADVANCE(15);
      if (lookahead == '/') ADVANCE(19);
      if (lookahead == '<') ADVANCE(20);
      if (lookahead == '=') ADVANCE(5);
      if (lookahead == '>') ADVANCE(25);
      if (lookahead == ']') ADVANCE(27);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(31);
      if (lookahead == '/') ADVANCE(33);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0) ADVANCE(34);
      END_STATE();
    case 4:
      if (lookahead == '=') ADVANCE(23);
      END_STATE();
    case 5:
      if (lookahead == '=') ADVANCE(22);
      END_STATE();
    case 6:
      if (lookahead == '"' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't') ADVANCE(35);
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 8:
      if (eof) ADVANCE(9);
      if (lookahead == '!') ADVANCE(14);
      if (lookahead == '"') ADVANCE(31);
      if (lookahead == '(') ADVANCE(11);
      if (lookahead == ')') ADVANCE(12);
      if (lookahead == '*') ADVANCE(18);
      if (lookahead == '+') ADVANCE(17);
      if (lookahead == ',') ADVANCE(13);
      if (lookahead == '-') ADVANCE(16);
      if (lookahead == '/') ADVANCE(19);
      if (lookahead == '<') ADVANCE(20);
      if (lookahead == '=') ADVANCE(5);
      if (lookahead == '>') ADVANCE(25);
      if (lookahead == '[') ADVANCE(26);
      if (lookahead == ']') ADVANCE(27);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(8)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_shell_bang);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_BANG);
      if (lookahead == '=') ADVANCE(23);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(36);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(21);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(24);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_unescaped_double_string_fragment);
      if (lookahead == '/') ADVANCE(33);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(34);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_unescaped_double_string_fragment);
      if (lookahead == '/') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(34);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_unescaped_double_string_fragment);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(40);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '/') ADVANCE(39);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(40);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '/') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(40);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(40);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'a') ADVANCE(1);
      if (lookahead == 'f') ADVANCE(2);
      if (lookahead == 'n') ADVANCE(3);
      if (lookahead == 'o') ADVANCE(4);
      if (lookahead == 't') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'n') ADVANCE(6);
      END_STATE();
    case 2:
      if (lookahead == 'a') ADVANCE(7);
      END_STATE();
    case 3:
      if (lookahead == 'i') ADVANCE(8);
      END_STATE();
    case 4:
      if (lookahead == 'r') ADVANCE(9);
      END_STATE();
    case 5:
      if (lookahead == 'r') ADVANCE(10);
      END_STATE();
    case 6:
      if (lookahead == 'd') ADVANCE(11);
      END_STATE();
    case 7:
      if (lookahead == 'l') ADVANCE(12);
      END_STATE();
    case 8:
      if (lookahead == 'l') ADVANCE(13);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_or);
      END_STATE();
    case 10:
      if (lookahead == 'u') ADVANCE(14);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_and);
      END_STATE();
    case 12:
      if (lookahead == 's') ADVANCE(15);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_nil);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 2},
  [58] = {.lex_state = 2},
  [59] = {.lex_state = 2},
  [60] = {.lex_state = 2},
  [61] = {.lex_state = 2},
  [62] = {.lex_state = 2},
  [63] = {.lex_state = 2},
  [64] = {.lex_state = 2},
  [65] = {.lex_state = 2},
  [66] = {.lex_state = 2},
  [67] = {.lex_state = 2},
  [68] = {.lex_state = 2},
  [69] = {.lex_state = 2},
  [70] = {.lex_state = 2},
  [71] = {.lex_state = 2},
  [72] = {.lex_state = 2},
  [73] = {.lex_state = 2},
  [74] = {.lex_state = 2},
  [75] = {.lex_state = 2},
  [76] = {.lex_state = 2},
  [77] = {.lex_state = 2},
  [78] = {.lex_state = 2},
  [79] = {.lex_state = 2},
  [80] = {.lex_state = 2},
  [81] = {.lex_state = 2},
  [82] = {.lex_state = 2},
  [83] = {.lex_state = 2},
  [84] = {.lex_state = 2},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 3},
  [87] = {.lex_state = 3},
  [88] = {.lex_state = 3},
  [89] = {.lex_state = 3},
  [90] = {.lex_state = 3},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 3},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 38},
  [97] = {.lex_state = 0},
  [98] = {(TSStateId)(-1)},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_shell_bang] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
    [anon_sym_or] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_nil] = ACTIONS(1),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(97),
    [sym__expression] = STATE(11),
    [sym_parenthesized_expression] = STATE(2),
    [sym_call] = STATE(2),
    [sym_unary_expression] = STATE(2),
    [sym_binary_expression] = STATE(2),
    [sym_array] = STATE(2),
    [sym__primary] = STATE(2),
    [sym_string] = STATE(3),
    [sym_boolean] = STATE(3),
    [sym_comment] = STATE(1),
    [aux_sym_source_file_repeat1] = STATE(26),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym_shell_bang] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_BANG] = ACTIONS(13),
    [anon_sym_DASH] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [anon_sym_DQUOTE] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [sym_nil] = ACTIONS(7),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [2] = {
    [sym_comment] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(25),
    [sym_identifier] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(25),
    [anon_sym_BANG] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_and] = ACTIONS(27),
    [anon_sym_or] = ACTIONS(27),
    [anon_sym_PLUS] = ACTIONS(25),
    [anon_sym_STAR] = ACTIONS(25),
    [anon_sym_SLASH] = ACTIONS(27),
    [anon_sym_LT] = ACTIONS(27),
    [anon_sym_LT_EQ] = ACTIONS(25),
    [anon_sym_EQ_EQ] = ACTIONS(25),
    [anon_sym_BANG_EQ] = ACTIONS(25),
    [anon_sym_GT_EQ] = ACTIONS(25),
    [anon_sym_GT] = ACTIONS(27),
    [anon_sym_LBRACK] = ACTIONS(25),
    [sym_number] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(25),
    [anon_sym_true] = ACTIONS(27),
    [anon_sym_false] = ACTIONS(27),
    [sym_nil] = ACTIONS(27),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [3] = {
    [sym_comment] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(29),
    [sym_identifier] = ACTIONS(31),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_BANG] = ACTIONS(31),
    [anon_sym_DASH] = ACTIONS(31),
    [anon_sym_and] = ACTIONS(31),
    [anon_sym_or] = ACTIONS(31),
    [anon_sym_PLUS] = ACTIONS(29),
    [anon_sym_STAR] = ACTIONS(29),
    [anon_sym_SLASH] = ACTIONS(31),
    [anon_sym_LT] = ACTIONS(31),
    [anon_sym_LT_EQ] = ACTIONS(29),
    [anon_sym_EQ_EQ] = ACTIONS(29),
    [anon_sym_BANG_EQ] = ACTIONS(29),
    [anon_sym_GT_EQ] = ACTIONS(29),
    [anon_sym_GT] = ACTIONS(31),
    [anon_sym_LBRACK] = ACTIONS(29),
    [sym_number] = ACTIONS(29),
    [anon_sym_DQUOTE] = ACTIONS(29),
    [anon_sym_true] = ACTIONS(31),
    [anon_sym_false] = ACTIONS(31),
    [sym_nil] = ACTIONS(31),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [4] = {
    [sym_comment] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(33),
    [sym_identifier] = ACTIONS(35),
    [anon_sym_LPAREN] = ACTIONS(33),
    [anon_sym_BANG] = ACTIONS(35),
    [anon_sym_DASH] = ACTIONS(37),
    [anon_sym_and] = ACTIONS(39),
    [anon_sym_or] = ACTIONS(35),
    [anon_sym_PLUS] = ACTIONS(41),
    [anon_sym_STAR] = ACTIONS(43),
    [anon_sym_SLASH] = ACTIONS(45),
    [anon_sym_LT] = ACTIONS(47),
    [anon_sym_LT_EQ] = ACTIONS(49),
    [anon_sym_EQ_EQ] = ACTIONS(51),
    [anon_sym_BANG_EQ] = ACTIONS(51),
    [anon_sym_GT_EQ] = ACTIONS(49),
    [anon_sym_GT] = ACTIONS(47),
    [anon_sym_LBRACK] = ACTIONS(33),
    [sym_number] = ACTIONS(33),
    [anon_sym_DQUOTE] = ACTIONS(33),
    [anon_sym_true] = ACTIONS(35),
    [anon_sym_false] = ACTIONS(35),
    [sym_nil] = ACTIONS(35),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [5] = {
    [sym_comment] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(53),
    [sym_identifier] = ACTIONS(55),
    [anon_sym_LPAREN] = ACTIONS(53),
    [anon_sym_BANG] = ACTIONS(55),
    [anon_sym_DASH] = ACTIONS(55),
    [anon_sym_and] = ACTIONS(55),
    [anon_sym_or] = ACTIONS(55),
    [anon_sym_PLUS] = ACTIONS(53),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym_SLASH] = ACTIONS(55),
    [anon_sym_LT] = ACTIONS(55),
    [anon_sym_LT_EQ] = ACTIONS(53),
    [anon_sym_EQ_EQ] = ACTIONS(53),
    [anon_sym_BANG_EQ] = ACTIONS(53),
    [anon_sym_GT_EQ] = ACTIONS(53),
    [anon_sym_GT] = ACTIONS(55),
    [anon_sym_LBRACK] = ACTIONS(53),
    [sym_number] = ACTIONS(53),
    [anon_sym_DQUOTE] = ACTIONS(53),
    [anon_sym_true] = ACTIONS(55),
    [anon_sym_false] = ACTIONS(55),
    [sym_nil] = ACTIONS(55),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [6] = {
    [sym_comment] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(57),
    [sym_identifier] = ACTIONS(59),
    [anon_sym_LPAREN] = ACTIONS(57),
    [anon_sym_BANG] = ACTIONS(59),
    [anon_sym_DASH] = ACTIONS(59),
    [anon_sym_and] = ACTIONS(59),
    [anon_sym_or] = ACTIONS(59),
    [anon_sym_PLUS] = ACTIONS(57),
    [anon_sym_STAR] = ACTIONS(57),
    [anon_sym_SLASH] = ACTIONS(59),
    [anon_sym_LT] = ACTIONS(59),
    [anon_sym_LT_EQ] = ACTIONS(57),
    [anon_sym_EQ_EQ] = ACTIONS(57),
    [anon_sym_BANG_EQ] = ACTIONS(57),
    [anon_sym_GT_EQ] = ACTIONS(57),
    [anon_sym_GT] = ACTIONS(59),
    [anon_sym_LBRACK] = ACTIONS(57),
    [sym_number] = ACTIONS(57),
    [anon_sym_DQUOTE] = ACTIONS(57),
    [anon_sym_true] = ACTIONS(59),
    [anon_sym_false] = ACTIONS(59),
    [sym_nil] = ACTIONS(59),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [7] = {
    [sym_comment] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(33),
    [sym_identifier] = ACTIONS(35),
    [anon_sym_LPAREN] = ACTIONS(33),
    [anon_sym_BANG] = ACTIONS(35),
    [anon_sym_DASH] = ACTIONS(37),
    [anon_sym_and] = ACTIONS(35),
    [anon_sym_or] = ACTIONS(35),
    [anon_sym_PLUS] = ACTIONS(41),
    [anon_sym_STAR] = ACTIONS(43),
    [anon_sym_SLASH] = ACTIONS(45),
    [anon_sym_LT] = ACTIONS(47),
    [anon_sym_LT_EQ] = ACTIONS(49),
    [anon_sym_EQ_EQ] = ACTIONS(51),
    [anon_sym_BANG_EQ] = ACTIONS(51),
    [anon_sym_GT_EQ] = ACTIONS(49),
    [anon_sym_GT] = ACTIONS(47),
    [anon_sym_LBRACK] = ACTIONS(33),
    [sym_number] = ACTIONS(33),
    [anon_sym_DQUOTE] = ACTIONS(33),
    [anon_sym_true] = ACTIONS(35),
    [anon_sym_false] = ACTIONS(35),
    [sym_nil] = ACTIONS(35),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [8] = {
    [sym_comment] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(61),
    [sym_identifier] = ACTIONS(63),
    [anon_sym_LPAREN] = ACTIONS(61),
    [anon_sym_BANG] = ACTIONS(63),
    [anon_sym_DASH] = ACTIONS(63),
    [anon_sym_and] = ACTIONS(63),
    [anon_sym_or] = ACTIONS(63),
    [anon_sym_PLUS] = ACTIONS(61),
    [anon_sym_STAR] = ACTIONS(61),
    [anon_sym_SLASH] = ACTIONS(63),
    [anon_sym_LT] = ACTIONS(63),
    [anon_sym_LT_EQ] = ACTIONS(61),
    [anon_sym_EQ_EQ] = ACTIONS(61),
    [anon_sym_BANG_EQ] = ACTIONS(61),
    [anon_sym_GT_EQ] = ACTIONS(61),
    [anon_sym_GT] = ACTIONS(63),
    [anon_sym_LBRACK] = ACTIONS(61),
    [sym_number] = ACTIONS(61),
    [anon_sym_DQUOTE] = ACTIONS(61),
    [anon_sym_true] = ACTIONS(63),
    [anon_sym_false] = ACTIONS(63),
    [sym_nil] = ACTIONS(63),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [9] = {
    [sym_comment] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(65),
    [sym_identifier] = ACTIONS(67),
    [anon_sym_LPAREN] = ACTIONS(65),
    [anon_sym_BANG] = ACTIONS(67),
    [anon_sym_DASH] = ACTIONS(67),
    [anon_sym_and] = ACTIONS(67),
    [anon_sym_or] = ACTIONS(67),
    [anon_sym_PLUS] = ACTIONS(65),
    [anon_sym_STAR] = ACTIONS(65),
    [anon_sym_SLASH] = ACTIONS(67),
    [anon_sym_LT] = ACTIONS(67),
    [anon_sym_LT_EQ] = ACTIONS(65),
    [anon_sym_EQ_EQ] = ACTIONS(65),
    [anon_sym_BANG_EQ] = ACTIONS(65),
    [anon_sym_GT_EQ] = ACTIONS(65),
    [anon_sym_GT] = ACTIONS(67),
    [anon_sym_LBRACK] = ACTIONS(65),
    [sym_number] = ACTIONS(65),
    [anon_sym_DQUOTE] = ACTIONS(65),
    [anon_sym_true] = ACTIONS(67),
    [anon_sym_false] = ACTIONS(67),
    [sym_nil] = ACTIONS(67),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [10] = {
    [sym_comment] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(69),
    [sym_identifier] = ACTIONS(71),
    [anon_sym_LPAREN] = ACTIONS(69),
    [anon_sym_BANG] = ACTIONS(71),
    [anon_sym_DASH] = ACTIONS(71),
    [anon_sym_and] = ACTIONS(71),
    [anon_sym_or] = ACTIONS(71),
    [anon_sym_PLUS] = ACTIONS(69),
    [anon_sym_STAR] = ACTIONS(69),
    [anon_sym_SLASH] = ACTIONS(71),
    [anon_sym_LT] = ACTIONS(71),
    [anon_sym_LT_EQ] = ACTIONS(69),
    [anon_sym_EQ_EQ] = ACTIONS(69),
    [anon_sym_BANG_EQ] = ACTIONS(69),
    [anon_sym_GT_EQ] = ACTIONS(69),
    [anon_sym_GT] = ACTIONS(71),
    [anon_sym_LBRACK] = ACTIONS(69),
    [sym_number] = ACTIONS(69),
    [anon_sym_DQUOTE] = ACTIONS(69),
    [anon_sym_true] = ACTIONS(71),
    [anon_sym_false] = ACTIONS(71),
    [sym_nil] = ACTIONS(71),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [11] = {
    [sym_comment] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(73),
    [sym_identifier] = ACTIONS(75),
    [anon_sym_LPAREN] = ACTIONS(77),
    [anon_sym_BANG] = ACTIONS(75),
    [anon_sym_DASH] = ACTIONS(80),
    [anon_sym_and] = ACTIONS(39),
    [anon_sym_or] = ACTIONS(83),
    [anon_sym_PLUS] = ACTIONS(41),
    [anon_sym_STAR] = ACTIONS(43),
    [anon_sym_SLASH] = ACTIONS(45),
    [anon_sym_LT] = ACTIONS(47),
    [anon_sym_LT_EQ] = ACTIONS(49),
    [anon_sym_EQ_EQ] = ACTIONS(51),
    [anon_sym_BANG_EQ] = ACTIONS(51),
    [anon_sym_GT_EQ] = ACTIONS(49),
    [anon_sym_GT] = ACTIONS(47),
    [anon_sym_LBRACK] = ACTIONS(73),
    [sym_number] = ACTIONS(73),
    [anon_sym_DQUOTE] = ACTIONS(73),
    [anon_sym_true] = ACTIONS(75),
    [anon_sym_false] = ACTIONS(75),
    [sym_nil] = ACTIONS(75),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [12] = {
    [sym_comment] = STATE(12),
    [ts_builtin_sym_end] = ACTIONS(85),
    [sym_identifier] = ACTIONS(87),
    [anon_sym_LPAREN] = ACTIONS(85),
    [anon_sym_BANG] = ACTIONS(87),
    [anon_sym_DASH] = ACTIONS(87),
    [anon_sym_and] = ACTIONS(87),
    [anon_sym_or] = ACTIONS(87),
    [anon_sym_PLUS] = ACTIONS(85),
    [anon_sym_STAR] = ACTIONS(85),
    [anon_sym_SLASH] = ACTIONS(87),
    [anon_sym_LT] = ACTIONS(87),
    [anon_sym_LT_EQ] = ACTIONS(85),
    [anon_sym_EQ_EQ] = ACTIONS(85),
    [anon_sym_BANG_EQ] = ACTIONS(85),
    [anon_sym_GT_EQ] = ACTIONS(85),
    [anon_sym_GT] = ACTIONS(87),
    [anon_sym_LBRACK] = ACTIONS(85),
    [sym_number] = ACTIONS(85),
    [anon_sym_DQUOTE] = ACTIONS(85),
    [anon_sym_true] = ACTIONS(87),
    [anon_sym_false] = ACTIONS(87),
    [sym_nil] = ACTIONS(87),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [13] = {
    [sym_comment] = STATE(13),
    [ts_builtin_sym_end] = ACTIONS(89),
    [sym_identifier] = ACTIONS(91),
    [anon_sym_LPAREN] = ACTIONS(89),
    [anon_sym_BANG] = ACTIONS(91),
    [anon_sym_DASH] = ACTIONS(91),
    [anon_sym_and] = ACTIONS(91),
    [anon_sym_or] = ACTIONS(91),
    [anon_sym_PLUS] = ACTIONS(89),
    [anon_sym_STAR] = ACTIONS(89),
    [anon_sym_SLASH] = ACTIONS(91),
    [anon_sym_LT] = ACTIONS(91),
    [anon_sym_LT_EQ] = ACTIONS(89),
    [anon_sym_EQ_EQ] = ACTIONS(89),
    [anon_sym_BANG_EQ] = ACTIONS(89),
    [anon_sym_GT_EQ] = ACTIONS(89),
    [anon_sym_GT] = ACTIONS(91),
    [anon_sym_LBRACK] = ACTIONS(89),
    [sym_number] = ACTIONS(89),
    [anon_sym_DQUOTE] = ACTIONS(89),
    [anon_sym_true] = ACTIONS(91),
    [anon_sym_false] = ACTIONS(91),
    [sym_nil] = ACTIONS(91),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [14] = {
    [sym_comment] = STATE(14),
    [ts_builtin_sym_end] = ACTIONS(93),
    [sym_identifier] = ACTIONS(95),
    [anon_sym_LPAREN] = ACTIONS(93),
    [anon_sym_BANG] = ACTIONS(95),
    [anon_sym_DASH] = ACTIONS(95),
    [anon_sym_and] = ACTIONS(95),
    [anon_sym_or] = ACTIONS(95),
    [anon_sym_PLUS] = ACTIONS(93),
    [anon_sym_STAR] = ACTIONS(93),
    [anon_sym_SLASH] = ACTIONS(95),
    [anon_sym_LT] = ACTIONS(95),
    [anon_sym_LT_EQ] = ACTIONS(93),
    [anon_sym_EQ_EQ] = ACTIONS(93),
    [anon_sym_BANG_EQ] = ACTIONS(93),
    [anon_sym_GT_EQ] = ACTIONS(93),
    [anon_sym_GT] = ACTIONS(95),
    [anon_sym_LBRACK] = ACTIONS(93),
    [sym_number] = ACTIONS(93),
    [anon_sym_DQUOTE] = ACTIONS(93),
    [anon_sym_true] = ACTIONS(95),
    [anon_sym_false] = ACTIONS(95),
    [sym_nil] = ACTIONS(95),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [15] = {
    [sym_comment] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(33),
    [sym_identifier] = ACTIONS(35),
    [anon_sym_LPAREN] = ACTIONS(33),
    [anon_sym_BANG] = ACTIONS(35),
    [anon_sym_DASH] = ACTIONS(37),
    [anon_sym_and] = ACTIONS(35),
    [anon_sym_or] = ACTIONS(35),
    [anon_sym_PLUS] = ACTIONS(41),
    [anon_sym_STAR] = ACTIONS(43),
    [anon_sym_SLASH] = ACTIONS(45),
    [anon_sym_LT] = ACTIONS(35),
    [anon_sym_LT_EQ] = ACTIONS(33),
    [anon_sym_EQ_EQ] = ACTIONS(33),
    [anon_sym_BANG_EQ] = ACTIONS(33),
    [anon_sym_GT_EQ] = ACTIONS(33),
    [anon_sym_GT] = ACTIONS(35),
    [anon_sym_LBRACK] = ACTIONS(33),
    [sym_number] = ACTIONS(33),
    [anon_sym_DQUOTE] = ACTIONS(33),
    [anon_sym_true] = ACTIONS(35),
    [anon_sym_false] = ACTIONS(35),
    [sym_nil] = ACTIONS(35),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [16] = {
    [sym_comment] = STATE(16),
    [ts_builtin_sym_end] = ACTIONS(97),
    [sym_identifier] = ACTIONS(99),
    [anon_sym_LPAREN] = ACTIONS(97),
    [anon_sym_BANG] = ACTIONS(99),
    [anon_sym_DASH] = ACTIONS(99),
    [anon_sym_and] = ACTIONS(99),
    [anon_sym_or] = ACTIONS(99),
    [anon_sym_PLUS] = ACTIONS(97),
    [anon_sym_STAR] = ACTIONS(97),
    [anon_sym_SLASH] = ACTIONS(99),
    [anon_sym_LT] = ACTIONS(99),
    [anon_sym_LT_EQ] = ACTIONS(97),
    [anon_sym_EQ_EQ] = ACTIONS(97),
    [anon_sym_BANG_EQ] = ACTIONS(97),
    [anon_sym_GT_EQ] = ACTIONS(97),
    [anon_sym_GT] = ACTIONS(99),
    [anon_sym_LBRACK] = ACTIONS(97),
    [sym_number] = ACTIONS(97),
    [anon_sym_DQUOTE] = ACTIONS(97),
    [anon_sym_true] = ACTIONS(99),
    [anon_sym_false] = ACTIONS(99),
    [sym_nil] = ACTIONS(99),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [17] = {
    [sym_comment] = STATE(17),
    [ts_builtin_sym_end] = ACTIONS(101),
    [sym_identifier] = ACTIONS(103),
    [anon_sym_LPAREN] = ACTIONS(101),
    [anon_sym_BANG] = ACTIONS(103),
    [anon_sym_DASH] = ACTIONS(103),
    [anon_sym_and] = ACTIONS(103),
    [anon_sym_or] = ACTIONS(103),
    [anon_sym_PLUS] = ACTIONS(101),
    [anon_sym_STAR] = ACTIONS(101),
    [anon_sym_SLASH] = ACTIONS(103),
    [anon_sym_LT] = ACTIONS(103),
    [anon_sym_LT_EQ] = ACTIONS(101),
    [anon_sym_EQ_EQ] = ACTIONS(101),
    [anon_sym_BANG_EQ] = ACTIONS(101),
    [anon_sym_GT_EQ] = ACTIONS(101),
    [anon_sym_GT] = ACTIONS(103),
    [anon_sym_LBRACK] = ACTIONS(101),
    [sym_number] = ACTIONS(101),
    [anon_sym_DQUOTE] = ACTIONS(101),
    [anon_sym_true] = ACTIONS(103),
    [anon_sym_false] = ACTIONS(103),
    [sym_nil] = ACTIONS(103),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [18] = {
    [sym_comment] = STATE(18),
    [ts_builtin_sym_end] = ACTIONS(105),
    [sym_identifier] = ACTIONS(107),
    [anon_sym_LPAREN] = ACTIONS(105),
    [anon_sym_BANG] = ACTIONS(107),
    [anon_sym_DASH] = ACTIONS(107),
    [anon_sym_and] = ACTIONS(107),
    [anon_sym_or] = ACTIONS(107),
    [anon_sym_PLUS] = ACTIONS(105),
    [anon_sym_STAR] = ACTIONS(105),
    [anon_sym_SLASH] = ACTIONS(107),
    [anon_sym_LT] = ACTIONS(107),
    [anon_sym_LT_EQ] = ACTIONS(105),
    [anon_sym_EQ_EQ] = ACTIONS(105),
    [anon_sym_BANG_EQ] = ACTIONS(105),
    [anon_sym_GT_EQ] = ACTIONS(105),
    [anon_sym_GT] = ACTIONS(107),
    [anon_sym_LBRACK] = ACTIONS(105),
    [sym_number] = ACTIONS(105),
    [anon_sym_DQUOTE] = ACTIONS(105),
    [anon_sym_true] = ACTIONS(107),
    [anon_sym_false] = ACTIONS(107),
    [sym_nil] = ACTIONS(107),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [19] = {
    [sym_comment] = STATE(19),
    [ts_builtin_sym_end] = ACTIONS(33),
    [sym_identifier] = ACTIONS(35),
    [anon_sym_LPAREN] = ACTIONS(33),
    [anon_sym_BANG] = ACTIONS(35),
    [anon_sym_DASH] = ACTIONS(35),
    [anon_sym_and] = ACTIONS(35),
    [anon_sym_or] = ACTIONS(35),
    [anon_sym_PLUS] = ACTIONS(33),
    [anon_sym_STAR] = ACTIONS(33),
    [anon_sym_SLASH] = ACTIONS(35),
    [anon_sym_LT] = ACTIONS(35),
    [anon_sym_LT_EQ] = ACTIONS(33),
    [anon_sym_EQ_EQ] = ACTIONS(33),
    [anon_sym_BANG_EQ] = ACTIONS(33),
    [anon_sym_GT_EQ] = ACTIONS(33),
    [anon_sym_GT] = ACTIONS(35),
    [anon_sym_LBRACK] = ACTIONS(33),
    [sym_number] = ACTIONS(33),
    [anon_sym_DQUOTE] = ACTIONS(33),
    [anon_sym_true] = ACTIONS(35),
    [anon_sym_false] = ACTIONS(35),
    [sym_nil] = ACTIONS(35),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [20] = {
    [sym_comment] = STATE(20),
    [ts_builtin_sym_end] = ACTIONS(109),
    [sym_identifier] = ACTIONS(111),
    [anon_sym_LPAREN] = ACTIONS(109),
    [anon_sym_BANG] = ACTIONS(111),
    [anon_sym_DASH] = ACTIONS(111),
    [anon_sym_and] = ACTIONS(111),
    [anon_sym_or] = ACTIONS(111),
    [anon_sym_PLUS] = ACTIONS(109),
    [anon_sym_STAR] = ACTIONS(109),
    [anon_sym_SLASH] = ACTIONS(111),
    [anon_sym_LT] = ACTIONS(111),
    [anon_sym_LT_EQ] = ACTIONS(109),
    [anon_sym_EQ_EQ] = ACTIONS(109),
    [anon_sym_BANG_EQ] = ACTIONS(109),
    [anon_sym_GT_EQ] = ACTIONS(109),
    [anon_sym_GT] = ACTIONS(111),
    [anon_sym_LBRACK] = ACTIONS(109),
    [sym_number] = ACTIONS(109),
    [anon_sym_DQUOTE] = ACTIONS(109),
    [anon_sym_true] = ACTIONS(111),
    [anon_sym_false] = ACTIONS(111),
    [sym_nil] = ACTIONS(111),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [21] = {
    [sym_comment] = STATE(21),
    [ts_builtin_sym_end] = ACTIONS(113),
    [sym_identifier] = ACTIONS(115),
    [anon_sym_LPAREN] = ACTIONS(113),
    [anon_sym_BANG] = ACTIONS(115),
    [anon_sym_DASH] = ACTIONS(115),
    [anon_sym_and] = ACTIONS(115),
    [anon_sym_or] = ACTIONS(115),
    [anon_sym_PLUS] = ACTIONS(113),
    [anon_sym_STAR] = ACTIONS(113),
    [anon_sym_SLASH] = ACTIONS(115),
    [anon_sym_LT] = ACTIONS(115),
    [anon_sym_LT_EQ] = ACTIONS(113),
    [anon_sym_EQ_EQ] = ACTIONS(113),
    [anon_sym_BANG_EQ] = ACTIONS(113),
    [anon_sym_GT_EQ] = ACTIONS(113),
    [anon_sym_GT] = ACTIONS(115),
    [anon_sym_LBRACK] = ACTIONS(113),
    [sym_number] = ACTIONS(113),
    [anon_sym_DQUOTE] = ACTIONS(113),
    [anon_sym_true] = ACTIONS(115),
    [anon_sym_false] = ACTIONS(115),
    [sym_nil] = ACTIONS(115),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [22] = {
    [sym_comment] = STATE(22),
    [ts_builtin_sym_end] = ACTIONS(33),
    [sym_identifier] = ACTIONS(35),
    [anon_sym_LPAREN] = ACTIONS(33),
    [anon_sym_BANG] = ACTIONS(35),
    [anon_sym_DASH] = ACTIONS(37),
    [anon_sym_and] = ACTIONS(35),
    [anon_sym_or] = ACTIONS(35),
    [anon_sym_PLUS] = ACTIONS(41),
    [anon_sym_STAR] = ACTIONS(43),
    [anon_sym_SLASH] = ACTIONS(45),
    [anon_sym_LT] = ACTIONS(47),
    [anon_sym_LT_EQ] = ACTIONS(49),
    [anon_sym_EQ_EQ] = ACTIONS(33),
    [anon_sym_BANG_EQ] = ACTIONS(33),
    [anon_sym_GT_EQ] = ACTIONS(49),
    [anon_sym_GT] = ACTIONS(47),
    [anon_sym_LBRACK] = ACTIONS(33),
    [sym_number] = ACTIONS(33),
    [anon_sym_DQUOTE] = ACTIONS(33),
    [anon_sym_true] = ACTIONS(35),
    [anon_sym_false] = ACTIONS(35),
    [sym_nil] = ACTIONS(35),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [23] = {
    [sym_comment] = STATE(23),
    [ts_builtin_sym_end] = ACTIONS(33),
    [sym_identifier] = ACTIONS(35),
    [anon_sym_LPAREN] = ACTIONS(33),
    [anon_sym_BANG] = ACTIONS(35),
    [anon_sym_DASH] = ACTIONS(35),
    [anon_sym_and] = ACTIONS(35),
    [anon_sym_or] = ACTIONS(35),
    [anon_sym_PLUS] = ACTIONS(33),
    [anon_sym_STAR] = ACTIONS(43),
    [anon_sym_SLASH] = ACTIONS(45),
    [anon_sym_LT] = ACTIONS(35),
    [anon_sym_LT_EQ] = ACTIONS(33),
    [anon_sym_EQ_EQ] = ACTIONS(33),
    [anon_sym_BANG_EQ] = ACTIONS(33),
    [anon_sym_GT_EQ] = ACTIONS(33),
    [anon_sym_GT] = ACTIONS(35),
    [anon_sym_LBRACK] = ACTIONS(33),
    [sym_number] = ACTIONS(33),
    [anon_sym_DQUOTE] = ACTIONS(33),
    [anon_sym_true] = ACTIONS(35),
    [anon_sym_false] = ACTIONS(35),
    [sym_nil] = ACTIONS(35),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [24] = {
    [sym__expression] = STATE(11),
    [sym_parenthesized_expression] = STATE(2),
    [sym_call] = STATE(2),
    [sym_unary_expression] = STATE(2),
    [sym_binary_expression] = STATE(2),
    [sym_array] = STATE(2),
    [sym__primary] = STATE(2),
    [sym_string] = STATE(3),
    [sym_boolean] = STATE(3),
    [sym_comment] = STATE(24),
    [aux_sym_source_file_repeat1] = STATE(24),
    [ts_builtin_sym_end] = ACTIONS(117),
    [sym_identifier] = ACTIONS(119),
    [anon_sym_LPAREN] = ACTIONS(122),
    [anon_sym_BANG] = ACTIONS(125),
    [anon_sym_DASH] = ACTIONS(128),
    [anon_sym_LBRACK] = ACTIONS(131),
    [sym_number] = ACTIONS(134),
    [anon_sym_DQUOTE] = ACTIONS(137),
    [anon_sym_true] = ACTIONS(140),
    [anon_sym_false] = ACTIONS(140),
    [sym_nil] = ACTIONS(119),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [25] = {
    [sym__expression] = STATE(11),
    [sym_parenthesized_expression] = STATE(2),
    [sym_call] = STATE(2),
    [sym_unary_expression] = STATE(2),
    [sym_binary_expression] = STATE(2),
    [sym_array] = STATE(2),
    [sym__primary] = STATE(2),
    [sym_string] = STATE(3),
    [sym_boolean] = STATE(3),
    [sym_comment] = STATE(25),
    [aux_sym_source_file_repeat1] = STATE(24),
    [ts_builtin_sym_end] = ACTIONS(143),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_BANG] = ACTIONS(13),
    [anon_sym_DASH] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [anon_sym_DQUOTE] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [sym_nil] = ACTIONS(7),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [26] = {
    [sym__expression] = STATE(11),
    [sym_parenthesized_expression] = STATE(2),
    [sym_call] = STATE(2),
    [sym_unary_expression] = STATE(2),
    [sym_binary_expression] = STATE(2),
    [sym_array] = STATE(2),
    [sym__primary] = STATE(2),
    [sym_string] = STATE(3),
    [sym_boolean] = STATE(3),
    [sym_comment] = STATE(26),
    [aux_sym_source_file_repeat1] = STATE(24),
    [ts_builtin_sym_end] = ACTIONS(145),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_BANG] = ACTIONS(13),
    [anon_sym_DASH] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [anon_sym_DQUOTE] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [sym_nil] = ACTIONS(7),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
  [27] = {
    [sym__expression] = STATE(11),
    [sym_parenthesized_expression] = STATE(2),
    [sym_call] = STATE(2),
    [sym_unary_expression] = STATE(2),
    [sym_binary_expression] = STATE(2),
    [sym_array] = STATE(2),
    [sym__primary] = STATE(2),
    [sym_string] = STATE(3),
    [sym_boolean] = STATE(3),
    [sym_comment] = STATE(27),
    [aux_sym_source_file_repeat1] = STATE(25),
    [ts_builtin_sym_end] = ACTIONS(145),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_BANG] = ACTIONS(13),
    [anon_sym_DASH] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [anon_sym_DQUOTE] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [sym_nil] = ACTIONS(7),
    [anon_sym_SLASH_SLASH] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    ACTIONS(151), 1,
      anon_sym_RPAREN,
    ACTIONS(153), 1,
      anon_sym_BANG,
    ACTIONS(155), 1,
      anon_sym_DASH,
    ACTIONS(157), 1,
      anon_sym_LBRACK,
    ACTIONS(159), 1,
      sym_number,
    ACTIONS(161), 1,
      anon_sym_DQUOTE,
    STATE(28), 1,
      sym_comment,
    STATE(60), 1,
      sym__expression,
    ACTIONS(147), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(163), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(63), 2,
      sym_string,
      sym_boolean,
    STATE(65), 6,
      sym_parenthesized_expression,
      sym_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [51] = 14,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 1,
      anon_sym_BANG,
    ACTIONS(155), 1,
      anon_sym_DASH,
    ACTIONS(157), 1,
      anon_sym_LBRACK,
    ACTIONS(159), 1,
      sym_number,
    ACTIONS(161), 1,
      anon_sym_DQUOTE,
    ACTIONS(165), 1,
      anon_sym_RPAREN,
    STATE(29), 1,
      sym_comment,
    STATE(59), 1,
      sym__expression,
    ACTIONS(147), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(163), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(63), 2,
      sym_string,
      sym_boolean,
    STATE(65), 6,
      sym_parenthesized_expression,
      sym_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [102] = 14,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 1,
      anon_sym_BANG,
    ACTIONS(155), 1,
      anon_sym_DASH,
    ACTIONS(157), 1,
      anon_sym_LBRACK,
    ACTIONS(159), 1,
      sym_number,
    ACTIONS(161), 1,
      anon_sym_DQUOTE,
    ACTIONS(167), 1,
      anon_sym_RPAREN,
    STATE(30), 1,
      sym_comment,
    STATE(60), 1,
      sym__expression,
    ACTIONS(147), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(163), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(63), 2,
      sym_string,
      sym_boolean,
    STATE(65), 6,
      sym_parenthesized_expression,
      sym_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [153] = 14,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 1,
      anon_sym_BANG,
    ACTIONS(155), 1,
      anon_sym_DASH,
    ACTIONS(157), 1,
      anon_sym_LBRACK,
    ACTIONS(159), 1,
      sym_number,
    ACTIONS(161), 1,
      anon_sym_DQUOTE,
    ACTIONS(169), 1,
      anon_sym_RPAREN,
    STATE(31), 1,
      sym_comment,
    STATE(60), 1,
      sym__expression,
    ACTIONS(147), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(163), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(63), 2,
      sym_string,
      sym_boolean,
    STATE(65), 6,
      sym_parenthesized_expression,
      sym_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [204] = 14,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 1,
      anon_sym_BANG,
    ACTIONS(155), 1,
      anon_sym_DASH,
    ACTIONS(157), 1,
      anon_sym_LBRACK,
    ACTIONS(159), 1,
      sym_number,
    ACTIONS(161), 1,
      anon_sym_DQUOTE,
    ACTIONS(171), 1,
      anon_sym_RBRACK,
    STATE(32), 1,
      sym_comment,
    STATE(78), 1,
      sym__expression,
    ACTIONS(147), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(163), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(63), 2,
      sym_string,
      sym_boolean,
    STATE(65), 6,
      sym_parenthesized_expression,
      sym_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [255] = 14,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 1,
      anon_sym_BANG,
    ACTIONS(155), 1,
      anon_sym_DASH,
    ACTIONS(157), 1,
      anon_sym_LBRACK,
    ACTIONS(159), 1,
      sym_number,
    ACTIONS(161), 1,
      anon_sym_DQUOTE,
    ACTIONS(173), 1,
      anon_sym_RBRACK,
    STATE(33), 1,
      sym_comment,
    STATE(60), 1,
      sym__expression,
    ACTIONS(147), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(163), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(63), 2,
      sym_string,
      sym_boolean,
    STATE(65), 6,
      sym_parenthesized_expression,
      sym_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [306] = 14,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 1,
      anon_sym_BANG,
    ACTIONS(155), 1,
      anon_sym_DASH,
    ACTIONS(157), 1,
      anon_sym_LBRACK,
    ACTIONS(159), 1,
      sym_number,
    ACTIONS(161), 1,
      anon_sym_DQUOTE,
    ACTIONS(175), 1,
      anon_sym_RPAREN,
    STATE(34), 1,
      sym_comment,
    STATE(61), 1,
      sym__expression,
    ACTIONS(147), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(163), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(63), 2,
      sym_string,
      sym_boolean,
    STATE(65), 6,
      sym_parenthesized_expression,
      sym_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [357] = 14,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 1,
      anon_sym_BANG,
    ACTIONS(155), 1,
      anon_sym_DASH,
    ACTIONS(157), 1,
      anon_sym_LBRACK,
    ACTIONS(159), 1,
      sym_number,
    ACTIONS(161), 1,
      anon_sym_DQUOTE,
    ACTIONS(177), 1,
      anon_sym_RBRACK,
    STATE(35), 1,
      sym_comment,
    STATE(60), 1,
      sym__expression,
    ACTIONS(147), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(163), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(63), 2,
      sym_string,
      sym_boolean,
    STATE(65), 6,
      sym_parenthesized_expression,
      sym_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [408] = 14,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 1,
      anon_sym_BANG,
    ACTIONS(155), 1,
      anon_sym_DASH,
    ACTIONS(157), 1,
      anon_sym_LBRACK,
    ACTIONS(159), 1,
      sym_number,
    ACTIONS(161), 1,
      anon_sym_DQUOTE,
    ACTIONS(179), 1,
      anon_sym_RBRACK,
    STATE(36), 1,
      sym_comment,
    STATE(62), 1,
      sym__expression,
    ACTIONS(147), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(163), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(63), 2,
      sym_string,
      sym_boolean,
    STATE(65), 6,
      sym_parenthesized_expression,
      sym_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [459] = 14,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 1,
      anon_sym_BANG,
    ACTIONS(155), 1,
      anon_sym_DASH,
    ACTIONS(157), 1,
      anon_sym_LBRACK,
    ACTIONS(159), 1,
      sym_number,
    ACTIONS(161), 1,
      anon_sym_DQUOTE,
    ACTIONS(181), 1,
      anon_sym_RBRACK,
    STATE(37), 1,
      sym_comment,
    STATE(60), 1,
      sym__expression,
    ACTIONS(147), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(163), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(63), 2,
      sym_string,
      sym_boolean,
    STATE(65), 6,
      sym_parenthesized_expression,
      sym_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [510] = 14,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 1,
      anon_sym_BANG,
    ACTIONS(155), 1,
      anon_sym_DASH,
    ACTIONS(157), 1,
      anon_sym_LBRACK,
    ACTIONS(159), 1,
      sym_number,
    ACTIONS(161), 1,
      anon_sym_DQUOTE,
    ACTIONS(183), 1,
      anon_sym_RPAREN,
    STATE(38), 1,
      sym_comment,
    STATE(60), 1,
      sym__expression,
    ACTIONS(147), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(163), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(63), 2,
      sym_string,
      sym_boolean,
    STATE(65), 6,
      sym_parenthesized_expression,
      sym_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [561] = 14,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 1,
      anon_sym_BANG,
    ACTIONS(155), 1,
      anon_sym_DASH,
    ACTIONS(157), 1,
      anon_sym_LBRACK,
    ACTIONS(159), 1,
      sym_number,
    ACTIONS(161), 1,
      anon_sym_DQUOTE,
    ACTIONS(185), 1,
      anon_sym_RBRACK,
    STATE(39), 1,
      sym_comment,
    STATE(60), 1,
      sym__expression,
    ACTIONS(147), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(163), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(63), 2,
      sym_string,
      sym_boolean,
    STATE(65), 6,
      sym_parenthesized_expression,
      sym_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [612] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_BANG,
    ACTIONS(15), 1,
      anon_sym_DASH,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      sym_number,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    STATE(23), 1,
      sym__expression,
    STATE(40), 1,
      sym_comment,
    ACTIONS(7), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(3), 2,
      sym_string,
      sym_boolean,
    STATE(2), 6,
      sym_parenthesized_expression,
      sym_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [660] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 1,
      anon_sym_BANG,
    ACTIONS(155), 1,
      anon_sym_DASH,
    ACTIONS(157), 1,
      anon_sym_LBRACK,
    ACTIONS(159), 1,
      sym_number,
    ACTIONS(161), 1,
      anon_sym_DQUOTE,
    STATE(41), 1,
      sym_comment,
    STATE(73), 1,
      sym__expression,
    ACTIONS(147), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(163), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(63), 2,
      sym_string,
      sym_boolean,
    STATE(65), 6,
      sym_parenthesized_expression,
      sym_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [708] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_BANG,
    ACTIONS(15), 1,
      anon_sym_DASH,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      sym_number,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    STATE(19), 1,
      sym__expression,
    STATE(42), 1,
      sym_comment,
    ACTIONS(7), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(3), 2,
      sym_string,
      sym_boolean,
    STATE(2), 6,
      sym_parenthesized_expression,
      sym_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [756] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_BANG,
    ACTIONS(15), 1,
      anon_sym_DASH,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      sym_number,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    STATE(15), 1,
      sym__expression,
    STATE(43), 1,
      sym_comment,
    ACTIONS(7), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(3), 2,
      sym_string,
      sym_boolean,
    STATE(2), 6,
      sym_parenthesized_expression,
      sym_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [804] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_BANG,
    ACTIONS(15), 1,
      anon_sym_DASH,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      sym_number,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    STATE(22), 1,
      sym__expression,
    STATE(44), 1,
      sym_comment,
    ACTIONS(7), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(3), 2,
      sym_string,
      sym_boolean,
    STATE(2), 6,
      sym_parenthesized_expression,
      sym_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [852] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 1,
      anon_sym_BANG,
    ACTIONS(155), 1,
      anon_sym_DASH,
    ACTIONS(157), 1,
      anon_sym_LBRACK,
    ACTIONS(159), 1,
      sym_number,
    ACTIONS(161), 1,
      anon_sym_DQUOTE,
    STATE(45), 1,
      sym_comment,
    STATE(84), 1,
      sym__expression,
    ACTIONS(147), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(163), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(63), 2,
      sym_string,
      sym_boolean,
    STATE(65), 6,
      sym_parenthesized_expression,
      sym_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [900] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 1,
      anon_sym_BANG,
    ACTIONS(155), 1,
      anon_sym_DASH,
    ACTIONS(157), 1,
      anon_sym_LBRACK,
    ACTIONS(159), 1,
      sym_number,
    ACTIONS(161), 1,
      anon_sym_DQUOTE,
    STATE(46), 1,
      sym_comment,
    STATE(83), 1,
      sym__expression,
    ACTIONS(147), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(163), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(63), 2,
      sym_string,
      sym_boolean,
    STATE(65), 6,
      sym_parenthesized_expression,
      sym_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [948] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_BANG,
    ACTIONS(15), 1,
      anon_sym_DASH,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      sym_number,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    STATE(17), 1,
      sym__expression,
    STATE(47), 1,
      sym_comment,
    ACTIONS(7), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(3), 2,
      sym_string,
      sym_boolean,
    STATE(2), 6,
      sym_parenthesized_expression,
      sym_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [996] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 1,
      anon_sym_BANG,
    ACTIONS(155), 1,
      anon_sym_DASH,
    ACTIONS(157), 1,
      anon_sym_LBRACK,
    ACTIONS(159), 1,
      sym_number,
    ACTIONS(161), 1,
      anon_sym_DQUOTE,
    STATE(48), 1,
      sym_comment,
    STATE(66), 1,
      sym__expression,
    ACTIONS(147), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(163), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(63), 2,
      sym_string,
      sym_boolean,
    STATE(65), 6,
      sym_parenthesized_expression,
      sym_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [1044] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_BANG,
    ACTIONS(15), 1,
      anon_sym_DASH,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      sym_number,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    STATE(4), 1,
      sym__expression,
    STATE(49), 1,
      sym_comment,
    ACTIONS(7), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(3), 2,
      sym_string,
      sym_boolean,
    STATE(2), 6,
      sym_parenthesized_expression,
      sym_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [1092] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 1,
      anon_sym_BANG,
    ACTIONS(155), 1,
      anon_sym_DASH,
    ACTIONS(157), 1,
      anon_sym_LBRACK,
    ACTIONS(159), 1,
      sym_number,
    ACTIONS(161), 1,
      anon_sym_DQUOTE,
    STATE(50), 1,
      sym_comment,
    STATE(74), 1,
      sym__expression,
    ACTIONS(147), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(163), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(63), 2,
      sym_string,
      sym_boolean,
    STATE(65), 6,
      sym_parenthesized_expression,
      sym_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [1140] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 1,
      anon_sym_BANG,
    ACTIONS(155), 1,
      anon_sym_DASH,
    ACTIONS(157), 1,
      anon_sym_LBRACK,
    ACTIONS(159), 1,
      sym_number,
    ACTIONS(161), 1,
      anon_sym_DQUOTE,
    STATE(51), 1,
      sym_comment,
    STATE(75), 1,
      sym__expression,
    ACTIONS(147), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(163), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(63), 2,
      sym_string,
      sym_boolean,
    STATE(65), 6,
      sym_parenthesized_expression,
      sym_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [1188] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_BANG,
    ACTIONS(15), 1,
      anon_sym_DASH,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      sym_number,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    STATE(7), 1,
      sym__expression,
    STATE(52), 1,
      sym_comment,
    ACTIONS(7), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(3), 2,
      sym_string,
      sym_boolean,
    STATE(2), 6,
      sym_parenthesized_expression,
      sym_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [1236] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 1,
      anon_sym_BANG,
    ACTIONS(155), 1,
      anon_sym_DASH,
    ACTIONS(157), 1,
      anon_sym_LBRACK,
    ACTIONS(159), 1,
      sym_number,
    ACTIONS(161), 1,
      anon_sym_DQUOTE,
    STATE(53), 1,
      sym_comment,
    STATE(60), 1,
      sym__expression,
    ACTIONS(147), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(163), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(63), 2,
      sym_string,
      sym_boolean,
    STATE(65), 6,
      sym_parenthesized_expression,
      sym_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [1284] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 1,
      anon_sym_BANG,
    ACTIONS(155), 1,
      anon_sym_DASH,
    ACTIONS(157), 1,
      anon_sym_LBRACK,
    ACTIONS(159), 1,
      sym_number,
    ACTIONS(161), 1,
      anon_sym_DQUOTE,
    STATE(54), 1,
      sym_comment,
    STATE(76), 1,
      sym__expression,
    ACTIONS(147), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(163), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(63), 2,
      sym_string,
      sym_boolean,
    STATE(65), 6,
      sym_parenthesized_expression,
      sym_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [1332] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 1,
      anon_sym_BANG,
    ACTIONS(155), 1,
      anon_sym_DASH,
    ACTIONS(157), 1,
      anon_sym_LBRACK,
    ACTIONS(159), 1,
      sym_number,
    ACTIONS(161), 1,
      anon_sym_DQUOTE,
    STATE(55), 1,
      sym_comment,
    STATE(77), 1,
      sym__expression,
    ACTIONS(147), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(163), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(63), 2,
      sym_string,
      sym_boolean,
    STATE(65), 6,
      sym_parenthesized_expression,
      sym_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [1380] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 1,
      anon_sym_BANG,
    ACTIONS(155), 1,
      anon_sym_DASH,
    ACTIONS(157), 1,
      anon_sym_LBRACK,
    ACTIONS(159), 1,
      sym_number,
    ACTIONS(161), 1,
      anon_sym_DQUOTE,
    STATE(56), 1,
      sym_comment,
    STATE(58), 1,
      sym__expression,
    ACTIONS(147), 2,
      sym_identifier,
      sym_nil,
    ACTIONS(163), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(63), 2,
      sym_string,
      sym_boolean,
    STATE(65), 6,
      sym_parenthesized_expression,
      sym_call,
      sym_unary_expression,
      sym_binary_expression,
      sym_array,
      sym__primary,
  [1428] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(57), 1,
      sym_comment,
    ACTIONS(115), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(113), 13,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DASH,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_RBRACK,
  [1455] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(189), 1,
      anon_sym_STAR,
    ACTIONS(191), 1,
      anon_sym_SLASH,
    STATE(58), 1,
      sym_comment,
    ACTIONS(187), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(193), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(195), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(33), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_and,
      anon_sym_or,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_RBRACK,
  [1490] = 14,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(189), 1,
      anon_sym_STAR,
    ACTIONS(191), 1,
      anon_sym_SLASH,
    ACTIONS(197), 1,
      anon_sym_LPAREN,
    ACTIONS(199), 1,
      anon_sym_RPAREN,
    ACTIONS(201), 1,
      anon_sym_COMMA,
    ACTIONS(203), 1,
      anon_sym_and,
    ACTIONS(205), 1,
      anon_sym_or,
    STATE(59), 1,
      sym_comment,
    STATE(95), 1,
      aux_sym_call_repeat1,
    ACTIONS(187), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(193), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(195), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(207), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1537] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(189), 1,
      anon_sym_STAR,
    ACTIONS(191), 1,
      anon_sym_SLASH,
    ACTIONS(197), 1,
      anon_sym_LPAREN,
    ACTIONS(203), 1,
      anon_sym_and,
    ACTIONS(205), 1,
      anon_sym_or,
    STATE(60), 1,
      sym_comment,
    ACTIONS(187), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(193), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(195), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(207), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(209), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1580] = 14,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(189), 1,
      anon_sym_STAR,
    ACTIONS(191), 1,
      anon_sym_SLASH,
    ACTIONS(197), 1,
      anon_sym_LPAREN,
    ACTIONS(203), 1,
      anon_sym_and,
    ACTIONS(205), 1,
      anon_sym_or,
    ACTIONS(211), 1,
      anon_sym_RPAREN,
    ACTIONS(213), 1,
      anon_sym_COMMA,
    STATE(61), 1,
      sym_comment,
    STATE(94), 1,
      aux_sym_call_repeat1,
    ACTIONS(187), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(193), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(195), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(207), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1627] = 14,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(189), 1,
      anon_sym_STAR,
    ACTIONS(191), 1,
      anon_sym_SLASH,
    ACTIONS(197), 1,
      anon_sym_LPAREN,
    ACTIONS(203), 1,
      anon_sym_and,
    ACTIONS(205), 1,
      anon_sym_or,
    ACTIONS(215), 1,
      anon_sym_COMMA,
    ACTIONS(217), 1,
      anon_sym_RBRACK,
    STATE(62), 1,
      sym_comment,
    STATE(91), 1,
      aux_sym_call_repeat1,
    ACTIONS(187), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(193), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(195), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(207), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [1674] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(63), 1,
      sym_comment,
    ACTIONS(31), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(29), 13,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DASH,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_RBRACK,
  [1701] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(64), 1,
      sym_comment,
    ACTIONS(67), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(65), 13,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DASH,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_RBRACK,
  [1728] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(65), 1,
      sym_comment,
    ACTIONS(27), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(25), 13,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DASH,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_RBRACK,
  [1755] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(66), 1,
      sym_comment,
    ACTIONS(103), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(101), 13,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DASH,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_RBRACK,
  [1782] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(67), 1,
      sym_comment,
    ACTIONS(107), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(105), 13,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DASH,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_RBRACK,
  [1809] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(68), 1,
      sym_comment,
    ACTIONS(111), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(109), 13,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DASH,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_RBRACK,
  [1836] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(69), 1,
      sym_comment,
    ACTIONS(71), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(69), 13,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DASH,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_RBRACK,
  [1863] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(70), 1,
      sym_comment,
    ACTIONS(63), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(61), 13,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DASH,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_RBRACK,
  [1890] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(71), 1,
      sym_comment,
    ACTIONS(55), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(53), 13,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DASH,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_RBRACK,
  [1917] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(72), 1,
      sym_comment,
    ACTIONS(91), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(89), 13,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DASH,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_RBRACK,
  [1944] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(189), 1,
      anon_sym_STAR,
    ACTIONS(191), 1,
      anon_sym_SLASH,
    STATE(73), 1,
      sym_comment,
    ACTIONS(35), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(33), 12,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DASH,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_RBRACK,
  [1975] = 9,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(189), 1,
      anon_sym_STAR,
    ACTIONS(191), 1,
      anon_sym_SLASH,
    STATE(74), 1,
      sym_comment,
    ACTIONS(187), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(193), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(195), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(207), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(33), 6,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_and,
      anon_sym_or,
      anon_sym_RBRACK,
  [2012] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(189), 1,
      anon_sym_STAR,
    ACTIONS(191), 1,
      anon_sym_SLASH,
    ACTIONS(203), 1,
      anon_sym_and,
    STATE(75), 1,
      sym_comment,
    ACTIONS(187), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(193), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(195), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(207), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(33), 5,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_or,
      anon_sym_RBRACK,
  [2051] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(76), 1,
      sym_comment,
    ACTIONS(35), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(33), 13,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DASH,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_RBRACK,
  [2078] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(189), 1,
      anon_sym_STAR,
    ACTIONS(191), 1,
      anon_sym_SLASH,
    STATE(77), 1,
      sym_comment,
    ACTIONS(35), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(187), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(33), 10,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_and,
      anon_sym_or,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_RBRACK,
  [2111] = 14,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(189), 1,
      anon_sym_STAR,
    ACTIONS(191), 1,
      anon_sym_SLASH,
    ACTIONS(197), 1,
      anon_sym_LPAREN,
    ACTIONS(203), 1,
      anon_sym_and,
    ACTIONS(205), 1,
      anon_sym_or,
    ACTIONS(219), 1,
      anon_sym_COMMA,
    ACTIONS(221), 1,
      anon_sym_RBRACK,
    STATE(78), 1,
      sym_comment,
    STATE(92), 1,
      aux_sym_call_repeat1,
    ACTIONS(187), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(193), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(195), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(207), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [2158] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(79), 1,
      sym_comment,
    ACTIONS(59), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(57), 13,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DASH,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_RBRACK,
  [2185] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(80), 1,
      sym_comment,
    ACTIONS(87), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(85), 13,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DASH,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_RBRACK,
  [2212] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(81), 1,
      sym_comment,
    ACTIONS(95), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(93), 13,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DASH,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_RBRACK,
  [2239] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    STATE(82), 1,
      sym_comment,
    ACTIONS(99), 3,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(97), 13,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_DASH,
      anon_sym_and,
      anon_sym_or,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_RBRACK,
  [2266] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(189), 1,
      anon_sym_STAR,
    ACTIONS(191), 1,
      anon_sym_SLASH,
    ACTIONS(197), 1,
      anon_sym_LPAREN,
    ACTIONS(203), 1,
      anon_sym_and,
    ACTIONS(205), 1,
      anon_sym_or,
    ACTIONS(223), 1,
      anon_sym_RPAREN,
    STATE(83), 1,
      sym_comment,
    ACTIONS(187), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(193), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(195), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(207), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [2307] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(189), 1,
      anon_sym_STAR,
    ACTIONS(191), 1,
      anon_sym_SLASH,
    ACTIONS(197), 1,
      anon_sym_LPAREN,
    ACTIONS(203), 1,
      anon_sym_and,
    ACTIONS(205), 1,
      anon_sym_or,
    ACTIONS(225), 1,
      anon_sym_RPAREN,
    STATE(84), 1,
      sym_comment,
    ACTIONS(187), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(193), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(195), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(207), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [2348] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(227), 1,
      anon_sym_COMMA,
    ACTIONS(209), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
    STATE(85), 2,
      sym_comment,
      aux_sym_call_repeat1,
  [2363] = 5,
    ACTIONS(230), 1,
      anon_sym_DQUOTE,
    ACTIONS(234), 1,
      anon_sym_SLASH_SLASH,
    STATE(86), 1,
      sym_comment,
    STATE(87), 1,
      aux_sym_string_repeat1,
    ACTIONS(232), 2,
      sym_unescaped_double_string_fragment,
      sym_escape_sequence,
  [2380] = 5,
    ACTIONS(234), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(236), 1,
      anon_sym_DQUOTE,
    STATE(87), 1,
      sym_comment,
    STATE(90), 1,
      aux_sym_string_repeat1,
    ACTIONS(232), 2,
      sym_unescaped_double_string_fragment,
      sym_escape_sequence,
  [2397] = 5,
    ACTIONS(234), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(238), 1,
      anon_sym_DQUOTE,
    STATE(88), 1,
      sym_comment,
    STATE(89), 1,
      aux_sym_string_repeat1,
    ACTIONS(232), 2,
      sym_unescaped_double_string_fragment,
      sym_escape_sequence,
  [2414] = 5,
    ACTIONS(234), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(240), 1,
      anon_sym_DQUOTE,
    STATE(89), 1,
      sym_comment,
    STATE(90), 1,
      aux_sym_string_repeat1,
    ACTIONS(232), 2,
      sym_unescaped_double_string_fragment,
      sym_escape_sequence,
  [2431] = 4,
    ACTIONS(234), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(242), 1,
      anon_sym_DQUOTE,
    ACTIONS(244), 2,
      sym_unescaped_double_string_fragment,
      sym_escape_sequence,
    STATE(90), 2,
      sym_comment,
      aux_sym_string_repeat1,
  [2446] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(173), 1,
      anon_sym_RBRACK,
    ACTIONS(247), 1,
      anon_sym_COMMA,
    STATE(85), 1,
      aux_sym_call_repeat1,
    STATE(91), 1,
      sym_comment,
  [2462] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(177), 1,
      anon_sym_RBRACK,
    ACTIONS(249), 1,
      anon_sym_COMMA,
    STATE(85), 1,
      aux_sym_call_repeat1,
    STATE(92), 1,
      sym_comment,
  [2478] = 4,
    ACTIONS(234), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(251), 1,
      anon_sym_DQUOTE,
    STATE(93), 1,
      sym_comment,
    ACTIONS(253), 2,
      sym_unescaped_double_string_fragment,
      sym_escape_sequence,
  [2492] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(183), 1,
      anon_sym_RPAREN,
    ACTIONS(255), 1,
      anon_sym_COMMA,
    STATE(85), 1,
      aux_sym_call_repeat1,
    STATE(94), 1,
      sym_comment,
  [2508] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(151), 1,
      anon_sym_RPAREN,
    ACTIONS(257), 1,
      anon_sym_COMMA,
    STATE(85), 1,
      aux_sym_call_repeat1,
    STATE(95), 1,
      sym_comment,
  [2524] = 3,
    ACTIONS(234), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(259), 1,
      aux_sym_comment_token1,
    STATE(96), 1,
      sym_comment,
  [2534] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_SLASH,
    ACTIONS(261), 1,
      ts_builtin_sym_end,
    STATE(97), 1,
      sym_comment,
  [2544] = 1,
    ACTIONS(263), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(28)] = 0,
  [SMALL_STATE(29)] = 51,
  [SMALL_STATE(30)] = 102,
  [SMALL_STATE(31)] = 153,
  [SMALL_STATE(32)] = 204,
  [SMALL_STATE(33)] = 255,
  [SMALL_STATE(34)] = 306,
  [SMALL_STATE(35)] = 357,
  [SMALL_STATE(36)] = 408,
  [SMALL_STATE(37)] = 459,
  [SMALL_STATE(38)] = 510,
  [SMALL_STATE(39)] = 561,
  [SMALL_STATE(40)] = 612,
  [SMALL_STATE(41)] = 660,
  [SMALL_STATE(42)] = 708,
  [SMALL_STATE(43)] = 756,
  [SMALL_STATE(44)] = 804,
  [SMALL_STATE(45)] = 852,
  [SMALL_STATE(46)] = 900,
  [SMALL_STATE(47)] = 948,
  [SMALL_STATE(48)] = 996,
  [SMALL_STATE(49)] = 1044,
  [SMALL_STATE(50)] = 1092,
  [SMALL_STATE(51)] = 1140,
  [SMALL_STATE(52)] = 1188,
  [SMALL_STATE(53)] = 1236,
  [SMALL_STATE(54)] = 1284,
  [SMALL_STATE(55)] = 1332,
  [SMALL_STATE(56)] = 1380,
  [SMALL_STATE(57)] = 1428,
  [SMALL_STATE(58)] = 1455,
  [SMALL_STATE(59)] = 1490,
  [SMALL_STATE(60)] = 1537,
  [SMALL_STATE(61)] = 1580,
  [SMALL_STATE(62)] = 1627,
  [SMALL_STATE(63)] = 1674,
  [SMALL_STATE(64)] = 1701,
  [SMALL_STATE(65)] = 1728,
  [SMALL_STATE(66)] = 1755,
  [SMALL_STATE(67)] = 1782,
  [SMALL_STATE(68)] = 1809,
  [SMALL_STATE(69)] = 1836,
  [SMALL_STATE(70)] = 1863,
  [SMALL_STATE(71)] = 1890,
  [SMALL_STATE(72)] = 1917,
  [SMALL_STATE(73)] = 1944,
  [SMALL_STATE(74)] = 1975,
  [SMALL_STATE(75)] = 2012,
  [SMALL_STATE(76)] = 2051,
  [SMALL_STATE(77)] = 2078,
  [SMALL_STATE(78)] = 2111,
  [SMALL_STATE(79)] = 2158,
  [SMALL_STATE(80)] = 2185,
  [SMALL_STATE(81)] = 2212,
  [SMALL_STATE(82)] = 2239,
  [SMALL_STATE(83)] = 2266,
  [SMALL_STATE(84)] = 2307,
  [SMALL_STATE(85)] = 2348,
  [SMALL_STATE(86)] = 2363,
  [SMALL_STATE(87)] = 2380,
  [SMALL_STATE(88)] = 2397,
  [SMALL_STATE(89)] = 2414,
  [SMALL_STATE(90)] = 2431,
  [SMALL_STATE(91)] = 2446,
  [SMALL_STATE(92)] = 2462,
  [SMALL_STATE(93)] = 2478,
  [SMALL_STATE(94)] = 2492,
  [SMALL_STATE(95)] = 2508,
  [SMALL_STATE(96)] = 2524,
  [SMALL_STATE(97)] = 2534,
  [SMALL_STATE(98)] = 2544,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1),
  [27] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__primary, 1),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__primary, 1),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, .production_id = 2),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, .production_id = 2),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 4),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 4),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 3),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized_expression, 3),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parenthesized_expression, 3),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1),
  [77] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1), SHIFT(29),
  [80] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1), SHIFT(40),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 4),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 4),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 3),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 3),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 5),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 5),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 6),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 6),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expression, 2, .production_id = 1),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_expression, 2, .production_id = 1),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 2),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 5),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 5),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [119] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(3),
  [122] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(46),
  [125] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(47),
  [128] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(47),
  [131] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(36),
  [134] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(3),
  [137] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(88),
  [140] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(9),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [147] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [155] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [163] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [191] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [193] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [227] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2), SHIFT_REPEAT(53),
  [230] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [234] = {.entry = {.count = 1, .reusable = false}}, SHIFT(96),
  [236] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [238] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [240] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [242] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2),
  [244] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(93),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [251] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 1),
  [253] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 1),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [259] = {.entry = {.count = 1, .reusable = false}}, SHIFT(98),
  [261] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_lx(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
